import type { Category, Product } from "./queries";

export const ADDITIONAL_CATEGORIES: Category[] = [
  {
    id: "cat-utensils-cookware",
    parent_id: null,
    name: "Cooking Utensils & Containers",
    slug: "utensils-cookware",
    icon: "🍳",
    image_url: "/images/household.jpg",
    sort_order: 25,
    is_active: true,
  },
  {
    id: "cat-misc-items",
    parent_id: null,
    name: "Miscellaneous & Home Needs",
    slug: "misc-items",
    icon: "📦",
    image_url: "/images/packaged.jpg",
    sort_order: 26,
    is_active: true,
  },
  // Subcategories
  {
    id: "sub-pulses-dal-millets",
    parent_id: "cat-pulses-dal",
    name: "Millets (Bajra / Jowar)",
    slug: "pulses-dal-millets",
    icon: "🌾",
    image_url: null,
    sort_order: 10,
    is_active: true,
  },
  {
    id: "sub-pulses-dal-whole-lentils",
    parent_id: "cat-pulses-dal",
    name: "Whole Lentils",
    slug: "pulses-dal-whole-lentils",
    icon: "🫘",
    image_url: null,
    sort_order: 11,
    is_active: true,
  },
  {
    id: "sub-spices-masala-exotic",
    parent_id: "cat-spices-masala",
    name: "Whole Exotic Spices",
    slug: "spices-masala-exotic",
    icon: "🌶️",
    image_url: null,
    sort_order: 18,
    is_active: true,
  },
  {
    id: "sub-oil-ghee-specialty",
    parent_id: "cat-oil-ghee",
    name: "Specialty Cooking Oils",
    slug: "oil-ghee-specialty",
    icon: "🛢️",
    image_url: null,
    sort_order: 9,
    is_active: true,
  },
  {
    id: "sub-utensils-pots-pans",
    parent_id: "cat-utensils-cookware",
    name: "Pots, Pans & Cookers",
    slug: "utensils-pots-pans",
    icon: "🍳",
    image_url: null,
    sort_order: 0,
    is_active: true,
  },
  {
    id: "sub-utensils-containers",
    parent_id: "cat-utensils-cookware",
    name: "Steel & Plastic Containers",
    slug: "utensils-containers",
    icon: "🥫",
    image_url: null,
    sort_order: 1,
    is_active: true,
  },
  {
    id: "sub-utensils-kitchen-tools",
    parent_id: "cat-utensils-cookware",
    name: "Kitchen Tools & Cutlery",
    slug: "utensils-kitchen-tools",
    icon: "🔪",
    image_url: null,
    sort_order: 2,
    is_active: true,
  },
  {
    id: "sub-misc-electrical",
    parent_id: "cat-misc-items",
    name: "Electrical & Batteries",
    slug: "misc-electrical",
    icon: "🔋",
    image_url: null,
    sort_order: 0,
    is_active: true,
  },
  {
    id: "sub-misc-household",
    parent_id: "cat-misc-items",
    name: "Pooja & Household Misc",
    slug: "misc-household",
    icon: "📦",
    image_url: null,
    sort_order: 1,
    is_active: true,
  },
];

export const ADDITIONAL_PRODUCTS: Product[] = [
  // 1. Grains & Pulses
  {
    id: "prod-chana-dal",
    name: "Chana Dal (Bengal Gram)",
    slug: "chana-dal",
    brand: "Local Mill",
    category_id: "pulses-dal",
    subcategory_id: null,
    description: "Protein-rich yellow split Bengal gram for delicious dal tadka.",
    image_url: "/images/products/chana-dal.svg",
    tags: ["chana dal", "pulses", "dal", "protein"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 85,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-chana-dal-500g",
        product_id: "prod-chana-dal",
        label: "500 g",
        mrp: 50,
        price: 44,
        stock: 40,
        low_stock_threshold: 10,
        sku: "CHANADAL-500G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-chana-dal-1kg",
        product_id: "prod-chana-dal",
        label: "1 kg",
        mrp: 95,
        price: 84,
        stock: 50,
        low_stock_threshold: 10,
        sku: "CHANADAL-1KG",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-urad-dal-dhuli",
    name: "Urad Dal Dhuli (White)",
    slug: "urad-dal-dhuli",
    brand: "Local Mill",
    category_id: "pulses-dal",
    subcategory_id: null,
    description: "Washed white split urad dal for dal makhani, idli and medu vada.",
    image_url: "/images/products/urad-dal.svg",
    tags: ["urad dal", "dal", "white urad"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 62,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-urad-dal-500g",
        product_id: "prod-urad-dal-dhuli",
        label: "500 g",
        mrp: 68,
        price: 59,
        stock: 30,
        low_stock_threshold: 10,
        sku: "URADDAL-500G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-urad-dal-1kg",
        product_id: "prod-urad-dal-dhuli",
        label: "1 kg",
        mrp: 130,
        price: 116,
        stock: 40,
        low_stock_threshold: 10,
        sku: "URADDAL-1KG",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-pearl-millet-bajra",
    name: "Pearl Millet (Desi Bajra)",
    slug: "pearl-millet-bajra",
    brand: "Farm Fresh",
    category_id: "pulses-dal",
    subcategory_id: null,
    description: "Nutritious whole grain pearl millet bajra for healthy rotis and khichdi.",
    image_url: "/images/products/pearl-millet-bajra.svg",
    tags: ["bajra", "millet", "grain", "desi"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 45,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-bajra-1kg",
        product_id: "prod-pearl-millet-bajra",
        label: "1 kg",
        mrp: 45,
        price: 38,
        stock: 50,
        low_stock_threshold: 10,
        sku: "BAJRA-1KG",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-bajra-5kg",
        product_id: "prod-pearl-millet-bajra",
        label: "5 kg",
        mrp: 210,
        price: 180,
        stock: 20,
        low_stock_threshold: 5,
        sku: "BAJRA-5KG",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-sorghum-jowar",
    name: "Sorghum (Desi Jowar)",
    slug: "sorghum-jowar",
    brand: "Farm Fresh",
    category_id: "pulses-dal",
    subcategory_id: null,
    description: "High fiber gluten-free whole jowar grains for energy and digestion.",
    image_url: "/images/products/sorghum-jowar.svg",
    tags: ["jowar", "sorghum", "grain", "gluten free"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 38,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-jowar-1kg",
        product_id: "prod-sorghum-jowar",
        label: "1 kg",
        mrp: 60,
        price: 52,
        stock: 40,
        low_stock_threshold: 10,
        sku: "JOWAR-1KG",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-black-chickpeas-kala-chana",
    name: "Black Chickpeas (Kala Chana)",
    slug: "black-chickpeas-kala-chana",
    brand: "Local Farm",
    category_id: "pulses-dal",
    subcategory_id: null,
    description: "Organic black chickpeas kala chana, rich in iron and dietary fiber.",
    image_url: "/images/products/kala-chana.svg",
    tags: ["kala chana", "chana", "pulses"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 90,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-kalachana-500g",
        product_id: "prod-black-chickpeas-kala-chana",
        label: "500 g",
        mrp: 48,
        price: 42,
        stock: 40,
        low_stock_threshold: 10,
        sku: "KALACHANA-500G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-kalachana-1kg",
        product_id: "prod-black-chickpeas-kala-chana",
        label: "1 kg",
        mrp: 90,
        price: 79,
        stock: 50,
        low_stock_threshold: 10,
        sku: "KALACHANA-1KG",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-whole-red-lentils-sabut-masoor",
    name: "Whole Red Lentils (Sabut Masoor)",
    slug: "whole-red-lentils-sabut-masoor",
    brand: "Local Farm",
    category_id: "pulses-dal",
    subcategory_id: null,
    description: "Unpolished whole brown-red masoor lentils for hearty village-style curry.",
    image_url: "/images/products/sabut-masoor.svg",
    tags: ["sabut masoor", "masoor", "dal"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 55,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-sabutmasoor-1kg",
        product_id: "prod-whole-red-lentils-sabut-masoor",
        label: "1 kg",
        mrp: 98,
        price: 86,
        stock: 35,
        low_stock_threshold: 10,
        sku: "SABUTMASOOR-1KG",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-green-gram-sabut-moong",
    name: "Green Gram Whole (Sabut Moong)",
    slug: "green-gram-sabut-moong",
    brand: "Local Farm",
    category_id: "pulses-dal",
    subcategory_id: null,
    description: "Whole green moong beans ideal for morning sprouts and nutritious dal.",
    image_url: "/images/products/sabut-moong.svg",
    tags: ["sabut moong", "green gram", "dal", "sprouts"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 75,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-sabutmoong-500g",
        product_id: "prod-green-gram-sabut-moong",
        label: "500 g",
        mrp: 65,
        price: 56,
        stock: 35,
        low_stock_threshold: 10,
        sku: "SABUTMOONG-500G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-sabutmoong-1kg",
        product_id: "prod-green-gram-sabut-moong",
        label: "1 kg",
        mrp: 125,
        price: 109,
        stock: 40,
        low_stock_threshold: 10,
        sku: "SABUTMOONG-1KG",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-black-lentils-urad-sabut",
    name: "Black Lentils (Urad Sabut Kali Dal)",
    slug: "black-lentils-urad-sabut",
    brand: "Local Farm",
    category_id: "pulses-dal",
    subcategory_id: null,
    description: "Whole black gram for rich authentic Dal Makhani and traditional curries.",
    image_url: "/images/products/urad-sabut.svg",
    tags: ["kali dal", "urad sabut", "dal makhani"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 68,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-uradsabut-1kg",
        product_id: "prod-black-lentils-urad-sabut",
        label: "1 kg",
        mrp: 135,
        price: 119,
        stock: 30,
        low_stock_threshold: 10,
        sku: "URADSABUT-1KG",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 2. Spices & Masala
  {
    id: "prod-catch-hing-asafoetida",
    name: "Catch Hing (Asafoetida)",
    slug: "catch-hing-asafoetida",
    brand: "Catch",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Strong aromatic compounded asafoetida powder for tadka.",
    image_url: "/images/products/catch-hing.svg",
    tags: ["hing", "asafoetida", "spice", "catch"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 110,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-hing-50g",
        product_id: "prod-catch-hing-asafoetida",
        label: "50 g",
        mrp: 85,
        price: 78,
        stock: 40,
        low_stock_threshold: 10,
        sku: "HING-50G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-green-cardamom-choti-elaichi",
    name: "Green Cardamom (Choti Elaichi)",
    slug: "green-cardamom-choti-elaichi",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Aromatic bold green cardamom pods for tea, desserts and biryanis.",
    image_url: "/images/products/cardamom.svg",
    tags: ["elaichi", "cardamom", "spice", "dessert"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 80,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-elaichi-50g",
        product_id: "prod-green-cardamom-choti-elaichi",
        label: "50 g",
        mrp: 180,
        price: 160,
        stock: 30,
        low_stock_threshold: 5,
        sku: "ELAICHI-50G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-elaichi-100g",
        product_id: "prod-green-cardamom-choti-elaichi",
        label: "100 g",
        mrp: 340,
        price: 299,
        stock: 20,
        low_stock_threshold: 5,
        sku: "ELAICHI-100G",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-cinnamon-sticks-dalchini",
    name: "Cinnamon Sticks (Dalchini)",
    slug: "cinnamon-sticks-dalchini",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Pure rolled bark whole cinnamon dalchini with rich sweet aroma.",
    image_url: "/images/products/cinnamon.svg",
    tags: ["dalchini", "cinnamon", "spice"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 45,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-dalchini-100g",
        product_id: "prod-cinnamon-sticks-dalchini",
        label: "100 g",
        mrp: 75,
        price: 65,
        stock: 30,
        low_stock_threshold: 5,
        sku: "DALCHINI-100G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-whole-cloves-laung",
    name: "Whole Cloves (Laung)",
    slug: "whole-cloves-laung",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Spicy and pungent whole cloves laung with natural essential oils.",
    image_url: "/images/products/cloves.svg",
    tags: ["laung", "cloves", "spice"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 50,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-laung-50g",
        product_id: "prod-whole-cloves-laung",
        label: "50 g",
        mrp: 60,
        price: 52,
        stock: 35,
        low_stock_threshold: 5,
        sku: "LAUNG-50G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-laung-100g",
        product_id: "prod-whole-cloves-laung",
        label: "100 g",
        mrp: 115,
        price: 99,
        stock: 25,
        low_stock_threshold: 5,
        sku: "LAUNG-100G",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-black-pepper-kali-mirch",
    name: "Black Pepper (Kali Mirch Whole)",
    slug: "black-pepper-kali-mirch",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Whole bold black peppercorns for intense aroma and seasoning.",
    image_url: "/images/products/black-pepper.svg",
    tags: ["kali mirch", "black pepper", "spice"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 95,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-kalimirch-100g",
        product_id: "prod-black-pepper-kali-mirch",
        label: "100 g",
        mrp: 110,
        price: 95,
        stock: 30,
        low_stock_threshold: 5,
        sku: "KALIMIRCH-100G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-fennel-seeds-saunf",
    name: "Fennel Seeds (Moti Saunf)",
    slug: "fennel-seeds-saunf",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Sweet aromatic green fennel seeds for cooking and mouth freshening.",
    image_url: "/images/products/fennel-seeds.svg",
    tags: ["saunf", "fennel", "spice", "mukhwas"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 65,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-saunf-100g",
        product_id: "prod-fennel-seeds-saunf",
        label: "100 g",
        mrp: 55,
        price: 48,
        stock: 40,
        low_stock_threshold: 10,
        sku: "SAUNF-100G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-fenugreek-seeds-methi",
    name: "Fenugreek Seeds (Methi Dana)",
    slug: "fenugreek-seeds-methi",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Clean yellow bitter-sweet methi seeds for pickles and curries.",
    image_url: "/images/products/methi-seeds.svg",
    tags: ["methi", "fenugreek", "spice"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 40,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-methi-100g",
        product_id: "prod-fenugreek-seeds-methi",
        label: "100 g",
        mrp: 30,
        price: 25,
        stock: 50,
        low_stock_threshold: 10,
        sku: "METHI-100G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-dry-mango-powder-amchur",
    name: "Dry Mango Powder (Amchur)",
    slug: "dry-mango-powder-amchur",
    brand: "Everest",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Tangy dried green mango powder for chaats, curries and parathas.",
    image_url: "/images/products/amchur.svg",
    tags: ["amchur", "mango powder", "spice", "everest"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 55,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-amchur-100g",
        product_id: "prod-dry-mango-powder-amchur",
        label: "100 g",
        mrp: 60,
        price: 52,
        stock: 40,
        low_stock_threshold: 10,
        sku: "AMCHUR-100G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-bay-leaves-tej-patta",
    name: "Bay Leaves (Tej Patta)",
    slug: "bay-leaves-tej-patta",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Aromatic dried bay leaves for authentic biryani, pulao and curries.",
    image_url: "/images/products/tej-patta.svg",
    tags: ["tej patta", "bay leaf", "spice"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 60,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-tejpatta-50g",
        product_id: "prod-bay-leaves-tej-patta",
        label: "50 g",
        mrp: 35,
        price: 28,
        stock: 50,
        low_stock_threshold: 10,
        sku: "TEJPATTA-50G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-pure-kashmiri-saffron-kesar",
    name: "Pure Kashmiri Saffron (Kesar)",
    slug: "pure-kashmiri-saffron-kesar",
    brand: "Baby Brand",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "100% pure organic Mongra grade Kashmiri kesar with intense aroma.",
    image_url: "/images/products/saffron-kesar.svg",
    tags: ["kesar", "saffron", "spice", "royal"],
    is_featured: true,
    is_popular: false,
    is_active: true,
    sold_count: 35,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-kesar-1g",
        product_id: "prod-pure-kashmiri-saffron-kesar",
        label: "1 g box",
        mrp: 240,
        price: 210,
        stock: 20,
        low_stock_threshold: 5,
        sku: "KESAR-1G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-carom-seeds-ajwain",
    name: "Carom Seeds (Desi Ajwain)",
    slug: "carom-seeds-ajwain",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Digestive fragrant carom seeds ajwain for pooris and snacks.",
    image_url: "/images/products/ajwain.svg",
    tags: ["ajwain", "carom", "spice"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 88,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-ajwain-100g",
        product_id: "prod-carom-seeds-ajwain",
        label: "100 g",
        mrp: 45,
        price: 38,
        stock: 50,
        low_stock_threshold: 10,
        sku: "AJWAIN-100G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-whole-nutmeg-jaiphal",
    name: "Whole Nutmeg (Jaiphal)",
    slug: "whole-nutmeg-jaiphal",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Whole aromatic nutmeg nuts jaiphal for desserts and biryanis.",
    image_url: "/images/products/nutmeg.svg",
    tags: ["jaiphal", "nutmeg", "spice"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 30,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-jaiphal-50g",
        product_id: "prod-whole-nutmeg-jaiphal",
        label: "50 g",
        mrp: 75,
        price: 65,
        stock: 25,
        low_stock_threshold: 5,
        sku: "JAIPHAL-50G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-star-anise-chakra-phool",
    name: "Star Anise (Chakra Phool)",
    slug: "star-anise-chakra-phool",
    brand: "Royal Spices",
    category_id: "spices-masala",
    subcategory_id: null,
    description: "Whole star anise chakra phool for authentic biryani and garam masala.",
    image_url: "/images/products/star-anise.svg",
    tags: ["chakra phool", "star anise", "spice"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 32,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-starise-50g",
        product_id: "prod-star-anise-chakra-phool",
        label: "50 g",
        mrp: 60,
        price: 52,
        stock: 25,
        low_stock_threshold: 5,
        sku: "STARISE-50G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 3. Oils & Ghee
  {
    id: "prod-fortune-soyabean-oil",
    name: "Fortune Soyabean Oil",
    slug: "fortune-soyabean-oil",
    brand: "Fortune",
    category_id: "oil-ghee",
    subcategory_id: null,
    description: "Light and healthy refined soybean cooking oil for daily cooking.",
    image_url: "/images/products/soyabean-oil.svg",
    tags: ["soyabean oil", "cooking oil", "fortune"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 140,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-soyaoil-1l",
        product_id: "prod-fortune-soyabean-oil",
        label: "1 L Pouch",
        mrp: 135,
        price: 118,
        stock: 50,
        low_stock_threshold: 10,
        sku: "SOYAOIL-1L",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-dhara-peanut-oil",
    name: "Dhara Refined Peanut Oil",
    slug: "dhara-peanut-oil",
    brand: "Dhara",
    category_id: "oil-ghee",
    subcategory_id: null,
    description: "Filtered pure groundnut peanut cooking oil for traditional tastes.",
    image_url: "/images/products/peanut-oil.svg",
    tags: ["peanut oil", "groundnut oil", "dhara"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 50,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-peanut-1l",
        product_id: "prod-dhara-peanut-oil",
        label: "1 L Bottle",
        mrp: 185,
        price: 168,
        stock: 30,
        low_stock_threshold: 10,
        sku: "PEANUT-1L",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-figaro-pure-olive-oil",
    name: "Figaro Pure Olive Oil",
    slug: "figaro-pure-olive-oil",
    brand: "Figaro",
    category_id: "oil-ghee",
    subcategory_id: null,
    description: "Imported pure Spanish olive oil for healthy heart and gourmet cooking.",
    image_url: "/images/products/olive-oil.svg",
    tags: ["olive oil", "figaro", "gourmet"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 35,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-figaro-500ml",
        product_id: "prod-figaro-pure-olive-oil",
        label: "500 ml",
        mrp: 390,
        price: 349,
        stock: 15,
        low_stock_threshold: 5,
        sku: "FIGARO-500ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-figaro-1l",
        product_id: "prod-figaro-pure-olive-oil",
        label: "1 L Tin",
        mrp: 750,
        price: 680,
        stock: 10,
        low_stock_threshold: 3,
        sku: "FIGARO-1L",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-tilsona-sesame-oil",
    name: "Tilsona Pure Sesame Oil (Til Tel)",
    slug: "tilsona-sesame-oil",
    brand: "Tilsona",
    category_id: "oil-ghee",
    subcategory_id: null,
    description: "Pure cold pressed sesame gingelly oil for puja and cooking.",
    image_url: "/images/products/sesame-oil.svg",
    tags: ["sesame oil", "til tel", "tilsona"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 45,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-til-500ml",
        product_id: "prod-tilsona-sesame-oil",
        label: "500 ml",
        mrp: 140,
        price: 125,
        stock: 25,
        low_stock_threshold: 5,
        sku: "TIL-500ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-fortune-rice-bran-oil",
    name: "Fortune Rice Bran Health Oil",
    slug: "fortune-rice-bran-oil",
    brand: "Fortune",
    category_id: "oil-ghee",
    subcategory_id: null,
    description: "Physically refined rice bran oil enriched with Gamma Oryzanol.",
    image_url: "/images/products/rice-bran-oil.svg",
    tags: ["rice bran oil", "fortune", "healthy"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 105,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-ricebran-1l",
        product_id: "prod-fortune-rice-bran-oil",
        label: "1 L Pouch",
        mrp: 140,
        price: 124,
        stock: 40,
        low_stock_threshold: 10,
        sku: "RICEBRAN-1L",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-dalda-vanaspati-ghee",
    name: "Dalda Vanaspati Ghee",
    slug: "dalda-vanaspati-ghee",
    brand: "Dalda",
    category_id: "oil-ghee",
    subcategory_id: null,
    description: "Traditional hydrogenated vegetable ghee for puris and festival sweets.",
    image_url: "/images/products/dalda-ghee.svg",
    tags: ["dalda", "vanaspati", "ghee"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 70,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-dalda-1l",
        product_id: "prod-dalda-vanaspati-ghee",
        label: "1 L Pouch",
        mrp: 115,
        price: 99,
        stock: 40,
        low_stock_threshold: 10,
        sku: "DALDA-1L",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 4. Dairy Products
  {
    id: "prod-amul-masti-dahi",
    name: "Amul Masti Dahi (Curd)",
    slug: "amul-masti-dahi",
    brand: "Amul",
    category_id: "dairy",
    subcategory_id: null,
    description: "Thick, creamy and delicious pasteurised curd from pure cow milk.",
    image_url: "/images/products/amul-dahi.svg",
    tags: ["dahi", "curd", "amul", "dairy"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 180,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-amuldahi-200g",
        product_id: "prod-amul-masti-dahi",
        label: "200 g Cup",
        mrp: 25,
        price: 24,
        stock: 50,
        low_stock_threshold: 10,
        sku: "AMULDAHI-200G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-amuldahi-400g",
        product_id: "prod-amul-masti-dahi",
        label: "400 g Pouch",
        mrp: 35,
        price: 33,
        stock: 40,
        low_stock_threshold: 10,
        sku: "AMULDAHI-400G",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-amul-fresh-malai-paneer",
    name: "Amul Fresh Malai Paneer",
    slug: "amul-fresh-malai-paneer",
    brand: "Amul",
    category_id: "dairy",
    subcategory_id: null,
    description: "Soft, rich and melt-in-mouth cottage cheese paneer block.",
    image_url: "/images/products/amul-paneer.svg",
    tags: ["paneer", "cottage cheese", "amul", "dairy"],
    is_featured: true,
    is_popular: true,
    is_active: true,
    sold_count: 195,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-amulpaneer-200g",
        product_id: "prod-amul-fresh-malai-paneer",
        label: "200 g Pack",
        mrp: 90,
        price: 85,
        stock: 40,
        low_stock_threshold: 10,
        sku: "AMULPANEER-200G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-amul-fresh-cream",
    name: "Amul Fresh Cream",
    slug: "amul-fresh-cream",
    brand: "Amul",
    category_id: "dairy",
    subcategory_id: null,
    description: "Sterilised low fat dairy cooking cream for desserts and gravies.",
    image_url: "/images/products/amul-cream.svg",
    tags: ["cream", "malai", "amul", "dairy"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 70,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-amulcream-250ml",
        product_id: "prod-amul-fresh-cream",
        label: "250 ml",
        mrp: 70,
        price: 66,
        stock: 30,
        low_stock_threshold: 5,
        sku: "AMULCREAM-250ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-amul-spiced-buttermilk",
    name: "Amul Spiced Buttermilk (Chhaachh)",
    slug: "amul-spiced-buttermilk",
    brand: "Amul",
    category_id: "dairy",
    subcategory_id: null,
    description: "Refreshing spiced buttermilk pouch with mint, ginger and rock salt.",
    image_url: "/images/products/amul-chhaachh.svg",
    tags: ["chhaachh", "buttermilk", "amul", "mattha"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 220,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-amulchhaach-200",
        product_id: "prod-amul-spiced-buttermilk",
        label: "200 ml",
        mrp: 15,
        price: 14,
        stock: 60,
        low_stock_threshold: 15,
        sku: "AMULCHHAACH-200",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-nestle-everyday-milk-powder",
    name: "Nestle Everyday Dairy Whitener Milk Powder",
    slug: "nestle-everyday-milk-powder",
    brand: "Nestle",
    category_id: "dairy",
    subcategory_id: null,
    description: "Rich dairy whitener milk powder for rich, thick and aromatic tea.",
    image_url: "/images/products/milk-powder.svg",
    tags: ["milk powder", "dairy whitener", "nestle"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 85,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-nestlemp-200g",
        product_id: "prod-nestle-everyday-milk-powder",
        label: "200 g",
        mrp: 110,
        price: 99,
        stock: 30,
        low_stock_threshold: 5,
        sku: "NESTLEMP-200G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
      {
        id: "var-nestlemp-400g",
        product_id: "prod-nestle-everyday-milk-powder",
        label: "400 g",
        mrp: 210,
        price: 189,
        stock: 20,
        low_stock_threshold: 5,
        sku: "NESTLEMP-400G",
        barcode: null,
        sort_order: 1,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-nestle-milkmaid-condensed-milk",
    name: "Nestle Milkmaid Sweetened Condensed Milk",
    slug: "nestle-milkmaid-condensed-milk",
    brand: "Nestle",
    category_id: "dairy",
    subcategory_id: null,
    description: "Sweetened condensed milk for festive kheer, halwa and desserts.",
    image_url: "/images/products/condensed-milk.svg",
    tags: ["condensed milk", "milkmaid", "nestle", "sweets"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 75,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-milkmaid-380g",
        product_id: "prod-nestle-milkmaid-condensed-milk",
        label: "380 g Tin",
        mrp: 145,
        price: 134,
        stock: 30,
        low_stock_threshold: 5,
        sku: "MILKMAID-380G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-amul-cheese-slices",
    name: "Amul Cheese Slices",
    slug: "amul-cheese-slices",
    brand: "Amul",
    category_id: "dairy",
    subcategory_id: null,
    description: "Individually wrapped processed cheese slices for sandwiches and burgers.",
    image_url: "/images/products/cheese-slices.svg",
    tags: ["cheese", "cheese slices", "amul"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 110,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-amulcheese-200g",
        product_id: "prod-amul-cheese-slices",
        label: "10 Slices (200g)",
        mrp: 145,
        price: 135,
        stock: 30,
        low_stock_threshold: 5,
        sku: "AMULCHEESE-200G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 5. Snacks & Sweets
  {
    id: "prod-haldiram-rasgulla-tin",
    name: "Haldiram Rasgulla Tin",
    slug: "haldiram-rasgulla-tin",
    brand: "Haldirams",
    category_id: "chocolates",
    subcategory_id: null,
    description: "Traditional spongy cottage cheese rasgulla balls in light sugar syrup.",
    image_url: "/images/products/rasgulla.svg",
    tags: ["rasgulla", "sweets", "mithai", "haldirams"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 90,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-rasgulla-1kg",
        product_id: "prod-haldiram-rasgulla-tin",
        label: "1 kg Tin",
        mrp: 240,
        price: 215,
        stock: 25,
        low_stock_threshold: 5,
        sku: "RASGULLA-1KG",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-haldiram-gulab-jamun-tin",
    name: "Haldiram Gulab Jamun Tin",
    slug: "haldiram-gulab-jamun-tin",
    brand: "Haldirams",
    category_id: "chocolates",
    subcategory_id: null,
    description: "Soft melt-in-mouth khoya gulab jamuns soaked in aromatic sugar syrup.",
    image_url: "/images/products/gulab-jamun.svg",
    tags: ["gulab jamun", "sweets", "mithai", "haldirams"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 95,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-gulabjamun-1kg",
        product_id: "prod-haldiram-gulab-jamun-tin",
        label: "1 kg Tin",
        mrp: 250,
        price: 225,
        stock: 25,
        low_stock_threshold: 5,
        sku: "GULABJAMUN-1KG",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-mtr-breakfast-poha",
    name: "MTR 3-Minute Breakfast Khatta Meetha Poha",
    slug: "mtr-breakfast-poha",
    brand: "MTR",
    category_id: "packaged-foods",
    subcategory_id: null,
    description: "Instant ready-to-eat spiced flattened rice poha cup in just 3 minutes.",
    image_url: "/images/products/mtr-poha.svg",
    tags: ["poha", "breakfast", "mtr", "ready to eat"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 50,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-mtrpoha-60g",
        product_id: "prod-mtr-breakfast-poha",
        label: "60 g Cup",
        mrp: 45,
        price: 40,
        stock: 40,
        low_stock_threshold: 10,
        sku: "MTRPOHA-60G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-mtr-instant-rava-upma",
    name: "MTR Instant Rava Upma Mix",
    slug: "mtr-instant-rava-upma",
    brand: "MTR",
    category_id: "packaged-foods",
    subcategory_id: null,
    description: "Instant savoury semolina upma breakfast mix with mustard and curry leaves.",
    image_url: "/images/products/mtr-upma.svg",
    tags: ["upma", "rava upma", "mtr", "breakfast"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 45,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-mtrupma-500g",
        product_id: "prod-mtr-instant-rava-upma",
        label: "500 g Pack",
        mrp: 95,
        price: 84,
        stock: 30,
        low_stock_threshold: 5,
        sku: "MTRUPMA-500G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 6. Beverages
  {
    id: "prod-lipton-green-tea-honey-lemon",
    name: "Lipton Green Tea Honey Lemon",
    slug: "lipton-green-tea-honey-lemon",
    brand: "Lipton",
    category_id: "tea-coffee",
    subcategory_id: null,
    description: "Antioxidant-rich soothing green tea bags with subtle honey lemon flavour.",
    image_url: "/images/products/green-tea.svg",
    tags: ["green tea", "lipton", "tea", "detox"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 78,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-liptongt-25",
        product_id: "prod-lipton-green-tea-honey-lemon",
        label: "25 Tea Bags",
        mrp: 190,
        price: 168,
        stock: 30,
        low_stock_threshold: 5,
        sku: "LIPTONGT-25",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-red-bull-energy-drink",
    name: "Red Bull Energy Drink",
    slug: "red-bull-energy-drink",
    brand: "Red Bull",
    category_id: "beverages",
    subcategory_id: null,
    description: "Vitalizes body and mind energy drink can with taurine and B-vitamins.",
    image_url: "/images/products/red-bull.svg",
    tags: ["red bull", "energy drink", "beverages"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 65,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-redbull-250ml",
        product_id: "prod-red-bull-energy-drink",
        label: "250 ml Can",
        mrp: 125,
        price: 115,
        stock: 40,
        low_stock_threshold: 10,
        sku: "REDBULL-250ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-amul-kool-cafe",
    name: "Amul Kool Cafe Flavoured Milk",
    slug: "amul-kool-cafe",
    brand: "Amul",
    category_id: "beverages",
    subcategory_id: null,
    description: "Chilled rich coffee flavoured dairy drink can.",
    image_url: "/images/products/amul-kool.svg",
    tags: ["amul kool", "flavoured milk", "beverages"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 90,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-amulcafe-200ml",
        product_id: "prod-amul-kool-cafe",
        label: "200 ml Can",
        mrp: 35,
        price: 32,
        stock: 40,
        low_stock_threshold: 10,
        sku: "AMULCAFE-200ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-real-tender-coconut-water",
    name: "Real Coconut Water (100% Tender)",
    slug: "real-tender-coconut-water",
    brand: "Real",
    category_id: "beverages",
    subcategory_id: null,
    description: "Natural refreshing tender coconut water rich in electrolytes.",
    image_url: "/images/products/coconut-water.svg",
    tags: ["coconut water", "nariyal pani", "real", "juice"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 130,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-coco-200ml",
        product_id: "prod-real-tender-coconut-water",
        label: "200 ml Tetra",
        mrp: 50,
        price: 45,
        stock: 50,
        low_stock_threshold: 10,
        sku: "COCO-200ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 7. Breakfast Items
  {
    id: "prod-britannia-whole-wheat-bread",
    name: "Britannia 100% Whole Wheat Bread",
    slug: "britannia-whole-wheat-bread",
    brand: "Britannia",
    category_id: "breakfast",
    subcategory_id: null,
    description: "Freshly baked whole wheat brown sliced sandwich bread loaf.",
    image_url: "/images/products/wheat-bread.svg",
    tags: ["bread", "wheat bread", "britannia", "breakfast"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 175,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-britbread-400g",
        product_id: "prod-britannia-whole-wheat-bread",
        label: "400 g Loaf",
        mrp: 45,
        price: 40,
        stock: 30,
        low_stock_threshold: 5,
        sku: "BRITBREAD-400G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-fresh-farm-white-eggs-6pcs",
    name: "Fresh Farm White Eggs (Pack of 6)",
    slug: "fresh-farm-white-eggs-6pcs",
    brand: "Poultry Fresh",
    category_id: "breakfast",
    subcategory_id: null,
    description: "Freshly farm-harvested Grade-A protein rich white eggs.",
    image_url: "/images/products/farm-eggs.svg",
    tags: ["eggs", "farm eggs", "breakfast", "protein"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 240,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-eggs-6pcs",
        product_id: "prod-fresh-farm-white-eggs-6pcs",
        label: "Pack of 6",
        mrp: 42,
        price: 38,
        stock: 50,
        low_stock_threshold: 15,
        sku: "EGGS-6PCS",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-kissan-mixed-fruit-jam",
    name: "Kissan Mixed Fruit Jam",
    slug: "kissan-mixed-fruit-jam",
    brand: "Kissan",
    category_id: "sauces-spreads",
    subcategory_id: null,
    description: "Sweet tangy spread made with the goodness of 8 real fruits.",
    image_url: "/images/products/kissan-jam.svg",
    tags: ["jam", "fruit jam", "kissan", "spread"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 92,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-kissanjam-500g",
        product_id: "prod-kissan-mixed-fruit-jam",
        label: "500 g Jar",
        mrp: 170,
        price: 149,
        stock: 30,
        low_stock_threshold: 5,
        sku: "KISSANJAM-500G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-pintola-peanut-butter-crunchy",
    name: "Pintola All Natural Peanut Butter",
    slug: "pintola-peanut-butter-crunchy",
    brand: "Pintola",
    category_id: "sauces-spreads",
    subcategory_id: null,
    description: "100% natural high protein crunchy roasted peanut spread.",
    image_url: "/images/products/peanut-butter.svg",
    tags: ["peanut butter", "pintola", "fitness", "spread"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 80,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-pintola-350g",
        product_id: "prod-pintola-peanut-butter-crunchy",
        label: "350 g",
        mrp: 175,
        price: 155,
        stock: 25,
        low_stock_threshold: 5,
        sku: "PINTOLA-350G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-kellogg-muesli-fruit-nut",
    name: "Kellogg Muesli Fruit Nut & Seeds",
    slug: "kellogg-muesli-fruit-nut",
    brand: "Kelloggs",
    category_id: "packaged-foods",
    subcategory_id: null,
    description: "Crunchy grains with almonds, raisins and cranberries for super breakfast.",
    image_url: "/images/products/muesli.svg",
    tags: ["muesli", "cereal", "kelloggs", "breakfast"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 42,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-muesli-500g",
        product_id: "prod-kellogg-muesli-fruit-nut",
        label: "500 g Pack",
        mrp: 340,
        price: 299,
        stock: 15,
        low_stock_threshold: 5,
        sku: "MUESLI-500G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-nutella-hazelnut-spread",
    name: "Nutella Hazelnut Cocoa Spread",
    slug: "nutella-hazelnut-spread",
    brand: "Ferrero",
    category_id: "sauces-spreads",
    subcategory_id: null,
    description: "Creamy hazelnut and cocoa breakfast spread loved by kids and adults.",
    image_url: "/images/products/nutella.svg",
    tags: ["nutella", "hazelnut spread", "chocolate spread"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 90,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-nutella-350g",
        product_id: "prod-nutella-hazelnut-spread",
        label: "350 g Jar",
        mrp: 390,
        price: 349,
        stock: 20,
        low_stock_threshold: 5,
        sku: "NUTELLA-350G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 8. Personal Care
  {
    id: "prod-dettol-original-soap",
    name: "Dettol Original Bathing Soap",
    slug: "dettol-original-soap",
    brand: "Dettol",
    category_id: "personal-care",
    subcategory_id: null,
    description: "Trusted antibacterial antiseptic germ protection bathing bar.",
    image_url: "/images/products/dettol-soap.svg",
    tags: ["dettol soap", "soap", "hygiene"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 210,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-dettolsoap-4",
        product_id: "prod-dettol-original-soap",
        label: "Pack of 4 (125g each)",
        mrp: 175,
        price: 152,
        stock: 40,
        low_stock_threshold: 10,
        sku: "DETTOLSOAP-4",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-head-shoulders-cool-menthol",
    name: "Head & Shoulders Cool Menthol Shampoo",
    slug: "head-shoulders-cool-menthol",
    brand: "Head & Shoulders",
    category_id: "hair-care",
    subcategory_id: null,
    description: "Anti-dandruff cool menthol refreshing cooling shampoo.",
    image_url: "/images/products/head-shoulders.svg",
    tags: ["shampoo", "head shoulders", "hair care"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 85,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-hns-180ml",
        product_id: "prod-head-shoulders-cool-menthol",
        label: "180 ml",
        mrp: 190,
        price: 169,
        stock: 30,
        low_stock_threshold: 5,
        sku: "HNS-180ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-oral-b-toothbrush-shiny-clean",
    name: "Oral-B Shiny Clean Toothbrush (Medium)",
    slug: "oral-b-toothbrush-shiny-clean",
    brand: "Oral-B",
    category_id: "oral-care",
    subcategory_id: null,
    description: "Cross action plaque remover bristles for deep dental cleaning.",
    image_url: "/images/products/oral-b-brush.svg",
    tags: ["toothbrush", "oral b", "oral care"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 140,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-oralb-3pk",
        product_id: "prod-oral-b-toothbrush-shiny-clean",
        label: "Buy 2 Get 1 Free",
        mrp: 60,
        price: 50,
        stock: 50,
        low_stock_threshold: 10,
        sku: "ORALB-3PK",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-gillette-foamy-shaving-foam",
    name: "Gillette Foamy Lemon Lime Shaving Foam",
    slug: "gillette-foamy-shaving-foam",
    brand: "Gillette",
    category_id: "personal-care",
    subcategory_id: null,
    description: "Thick extra rich creamy lather for a comfortable smooth shave.",
    image_url: "/images/products/shaving-foam.svg",
    tags: ["shaving foam", "gillette", "grooming"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 60,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-gillette-foam",
        product_id: "prod-gillette-foamy-shaving-foam",
        label: "196 g Can",
        mrp: 160,
        price: 142,
        stock: 25,
        low_stock_threshold: 5,
        sku: "GILLETTE-FOAM",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-nivea-body-lotion-deep-moisture",
    name: "Nivea Body Lotion Nourishing Deep Moisture",
    slug: "nivea-body-lotion-deep-moisture",
    brand: "Nivea",
    category_id: "personal-care",
    subcategory_id: null,
    description: "48-hour intensive deep moisture care nourishing body lotion.",
    image_url: "/images/products/nivea-lotion.svg",
    tags: ["body lotion", "nivea", "skincare"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 95,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-nivealotion-200",
        product_id: "prod-nivea-body-lotion-deep-moisture",
        label: "200 ml",
        mrp: 225,
        price: 195,
        stock: 25,
        low_stock_threshold: 5,
        sku: "NIVEALOTION-200",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-fogg-scent-deodorant",
    name: "Fogg Scent Master Deodorant for Men",
    slug: "fogg-scent-deodorant",
    brand: "Fogg",
    category_id: "personal-care",
    subcategory_id: null,
    description: "No gas 1000 sprays long lasting all-day fragrant body spray.",
    image_url: "/images/products/fogg-deo.svg",
    tags: ["deodorant", "fogg", "fragrance"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 120,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-fogg-120ml",
        product_id: "prod-fogg-scent-deodorant",
        label: "120 ml",
        mrp: 250,
        price: 199,
        stock: 30,
        low_stock_threshold: 5,
        sku: "FOGG-120ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-garnier-men-acno-fight-facewash",
    name: "Garnier Men Acno Fight Face Wash",
    slug: "garnier-men-acno-fight-facewash",
    brand: "Garnier",
    category_id: "personal-care",
    subcategory_id: null,
    description: "Anti-pimple charcoal clarifying face wash for deep oil cleaning.",
    image_url: "/images/products/garnier-facewash.svg",
    tags: ["facewash", "garnier", "skincare"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 105,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-garnier-100g",
        product_id: "prod-garnier-men-acno-fight-facewash",
        label: "100 g",
        mrp: 199,
        price: 175,
        stock: 30,
        low_stock_threshold: 5,
        sku: "GARNIER-100G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 9. Cleaning Supplies
  {
    id: "prod-colin-glass-cleaner-spray",
    name: "Colin Glass and Household Cleaner Spray",
    slug: "colin-glass-cleaner-spray",
    brand: "Colin",
    category_id: "household-cleaning",
    subcategory_id: null,
    description: "Shine booster streak-free glass and appliance cleaner spray.",
    image_url: "/images/products/colin-spray.svg",
    tags: ["colin", "glass cleaner", "cleaning"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 130,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-colin-500ml",
        product_id: "prod-colin-glass-cleaner-spray",
        label: "500 ml Spray",
        mrp: 110,
        price: 98,
        stock: 40,
        low_stock_threshold: 10,
        sku: "COLIN-500ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-pril-dishwash-gel-liquid",
    name: "Pril Kraft Dishwash Gel Liquid",
    slug: "pril-dishwash-gel-liquid",
    brand: "Pril",
    category_id: "household-cleaning",
    subcategory_id: null,
    description: "Active power drops grease remover dishwash cleaning liquid.",
    image_url: "/images/products/pril-liquid.svg",
    tags: ["dishwash liquid", "pril", "cleaning"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 145,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-pril-425ml",
        product_id: "prod-pril-dishwash-gel-liquid",
        label: "425 ml Bottle",
        mrp: 115,
        price: 99,
        stock: 40,
        low_stock_threshold: 10,
        sku: "PRIL-425ML",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-trishul-white-phenyl",
    name: "Trishul White Phenyl Floor Disinfectant",
    slug: "trishul-white-phenyl",
    brand: "Trishul",
    category_id: "household-cleaning",
    subcategory_id: null,
    description: "Pine scented white floor cleaning and germicidal disinfectant.",
    image_url: "/images/products/phenyl-bottle.svg",
    tags: ["phenyl", "floor cleaner", "disinfectant"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 160,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-phenyl-1l",
        product_id: "prod-trishul-white-phenyl",
        label: "1 L Bottle",
        mrp: 80,
        price: 68,
        stock: 50,
        low_stock_threshold: 10,
        sku: "PHENYL-1L",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-odonil-air-freshener-lavender",
    name: "Odonil Room Air Freshener Lavender Block",
    slug: "odonil-air-freshener-lavender",
    brand: "Odonil",
    category_id: "household-cleaning",
    subcategory_id: null,
    description: "Long lasting natural fragrance block for bathroom and living rooms.",
    image_url: "/images/products/odonil-block.svg",
    tags: ["air freshener", "odonil", "fragrance"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 170,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-odonil-50g",
        product_id: "prod-odonil-air-freshener-lavender",
        label: "50 g Block",
        mrp: 55,
        price: 48,
        stock: 50,
        low_stock_threshold: 10,
        sku: "ODONIL-50G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-shalimar-garbage-bags-medium",
    name: "Shalimar Premium Oxo-Biodegradable Garbage Bags",
    slug: "shalimar-garbage-bags-medium",
    brand: "Shalimar",
    category_id: "kitchen-essentials",
    subcategory_id: null,
    description: "Tear resistant medium dustbin trash bags 30 pcs roll with tie tape.",
    image_url: "/images/products/garbage-bags.svg",
    tags: ["garbage bags", "trash bags", "shalimar"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 110,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-garbage-30",
        product_id: "prod-shalimar-garbage-bags-medium",
        label: "Pack of 30 Bags",
        mrp: 95,
        price: 79,
        stock: 40,
        low_stock_threshold: 10,
        sku: "GARBAGE-30",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-gala-king-kong-grass-broom",
    name: "Gala King Kong Grass Broom (Jhaadu)",
    slug: "gala-king-kong-grass-broom",
    brand: "Gala",
    category_id: "household-cleaning",
    subcategory_id: null,
    description: "Heavy duty fine Meghalaya natural grass dust broom for clean sweeps.",
    image_url: "/images/products/gala-broom.svg",
    tags: ["jhaadu", "broom", "gala", "cleaning"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 140,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-gala-broom",
        product_id: "prod-gala-king-kong-grass-broom",
        label: "1 Pc",
        mrp: 150,
        price: 129,
        stock: 30,
        low_stock_threshold: 5,
        sku: "GALA-BROOM",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-scotch-brite-cotton-floor-mop",
    name: "Scotch-Brite Cotton Floor Mop (Pocha)",
    slug: "scotch-brite-cotton-floor-mop",
    brand: "Scotch-Brite",
    category_id: "household-cleaning",
    subcategory_id: null,
    description: "Loop end absorbent wet cotton floor cleaning mop with sturdy handle.",
    image_url: "/images/products/floor-mop.svg",
    tags: ["mop", "pocha", "scotch brite"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 85,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-scotch-mop",
        product_id: "prod-scotch-brite-cotton-floor-mop",
        label: "1 Pc with Handle",
        mrp: 280,
        price: 245,
        stock: 20,
        low_stock_threshold: 5,
        sku: "SCOTCH-MOP",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-plastic-water-bucket-18l",
    name: "Plastic Heavy Duty Water Bucket (Balti 18L)",
    slug: "plastic-water-bucket-18l",
    brand: "Milton",
    category_id: "household-cleaning",
    subcategory_id: null,
    description: "Sturdy virgin plastic bathroom and utility washing bucket.",
    image_url: "/images/products/water-bucket.svg",
    tags: ["bucket", "balti", "milton"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 65,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-bucket-18l",
        product_id: "prod-plastic-water-bucket-18l",
        label: "18 Litre Heavy",
        mrp: 180,
        price: 149,
        stock: 25,
        low_stock_threshold: 5,
        sku: "BUCKET-18L",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 10. Cooking Utensils & Cookware
  {
    id: "prod-hawkins-pressure-cooker-3l",
    name: "Hawkins Classic Aluminium Pressure Cooker (3L)",
    slug: "hawkins-pressure-cooker-3l",
    brand: "Hawkins",
    category_id: "utensils-cookware",
    subcategory_id: null,
    description: "Inner lid energy efficient virgin aluminium pressure cooker.",
    image_url: "/images/products/pressure-cooker.svg",
    tags: ["cooker", "pressure cooker", "hawkins", "utensils"],
    is_featured: true,
    is_popular: true,
    is_active: true,
    sold_count: 45,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-hawkins-3l",
        product_id: "prod-hawkins-pressure-cooker-3l",
        label: "3 Litre Inner Lid",
        mrp: 1450,
        price: 1299,
        stock: 10,
        low_stock_threshold: 2,
        sku: "HAWKINS-3L",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-prestige-nonstick-dosa-tawa",
    name: "Prestige Induction Base Non-Stick Dosa Tawa",
    slug: "prestige-nonstick-dosa-tawa",
    brand: "Prestige",
    category_id: "utensils-cookware",
    subcategory_id: null,
    description: "Durable scratch resistant flat pan tawa for crispy rotis, parathas & dosas.",
    image_url: "/images/products/dosa-tawa.svg",
    tags: ["tawa", "dosa tawa", "prestige", "cookware"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 60,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-prestige-tawa",
        product_id: "prod-prestige-nonstick-dosa-tawa",
        label: "28 cm Flat",
        mrp: 750,
        price: 599,
        stock: 15,
        low_stock_threshold: 3,
        sku: "PRESTIGE-TAWA",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-prestige-anodised-kadhai",
    name: "Prestige Heavy Hard Anodised Kadhai with Lid (2.5L)",
    slug: "prestige-anodised-kadhai",
    brand: "Prestige",
    category_id: "utensils-cookware",
    subcategory_id: null,
    description: "Deep frying wok kadhai with stainless lid for rich curries and vegetables.",
    image_url: "/images/products/anodised-kadhai.svg",
    tags: ["kadhai", "wok", "prestige", "cookware"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 55,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-prestige-kadhai",
        product_id: "prod-prestige-anodised-kadhai",
        label: "2.5 L with Glass Lid",
        mrp: 990,
        price: 799,
        stock: 12,
        low_stock_threshold: 3,
        sku: "PRESTIGE-KADHAI",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-bajaj-mixer-grinder-500w",
    name: "Bajaj Classic 500W Mixer Grinder with 3 Jars",
    slug: "bajaj-mixer-grinder-500w",
    brand: "Bajaj",
    category_id: "utensils-cookware",
    subcategory_id: null,
    description: "Heavy duty motor for dry and wet spice grinding with 3 stainless steel jars.",
    image_url: "/images/products/mixer-grinder.svg",
    tags: ["mixer grinder", "bajaj", "appliance"],
    is_featured: true,
    is_popular: false,
    is_active: true,
    sold_count: 28,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-bajaj-mixer",
        product_id: "prod-bajaj-mixer-grinder-500w",
        label: "500W with 3 SS Jars",
        mrp: 2800,
        price: 2299,
        stock: 8,
        low_stock_threshold: 2,
        sku: "BAJAJ-MIXER",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-wooden-chakla-belan-set",
    name: "Wooden Chakla Belan Set for Rotis",
    slug: "wooden-chakla-belan-set",
    brand: "Kitchen Craft",
    category_id: "utensils-cookware",
    subcategory_id: null,
    description: "Heavy pure Sheesham wood smooth rolling pin and board for perfect rotis.",
    image_url: "/images/products/chakla-belan.svg",
    tags: ["chakla belan", "rolling pin", "kitchen"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 85,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-chakla-belan",
        product_id: "prod-wooden-chakla-belan-set",
        label: "Pure Sheesham Wood",
        mrp: 350,
        price: 279,
        stock: 20,
        low_stock_threshold: 5,
        sku: "CHAKLA-BELAN",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-steel-knife-peeler-set",
    name: "Stainless Steel Kitchen Knife & Peeler Set",
    slug: "steel-knife-peeler-set",
    brand: "Kitchen Craft",
    category_id: "utensils-cookware",
    subcategory_id: null,
    description: "Laser sharp stainless steel vegetable cutting knife and ergonomic peeler.",
    image_url: "/images/products/knife-peeler.svg",
    tags: ["knife", "peeler", "cutlery"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 120,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-knife-set",
        product_id: "prod-steel-knife-peeler-set",
        label: "Knife + Peeler Set",
        mrp: 120,
        price: 89,
        stock: 40,
        low_stock_threshold: 10,
        sku: "KNIFE-SET",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-steel-storage-jars-4pcs",
    name: "Stainless Steel Airtight Kitchen Storage Jars (Pack of 4)",
    slug: "steel-storage-jars-4pcs",
    brand: "Kitchen Craft",
    category_id: "utensils-cookware",
    subcategory_id: null,
    description: "Rust-proof see-through window grocery storage dabba containers.",
    image_url: "/images/products/storage-jars.svg",
    tags: ["storage jars", "dabba", "steel container"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 65,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-steel-jars-4",
        product_id: "prod-steel-storage-jars-4pcs",
        label: "Set of 4 Containers",
        mrp: 550,
        price: 429,
        stock: 15,
        low_stock_threshold: 3,
        sku: "STEEL-JARS-4",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-steel-colander-chhalni",
    name: "Stainless Steel Mesh Tea & Flour Colander (Chhalni)",
    slug: "steel-colander-chhalni",
    brand: "Kitchen Craft",
    category_id: "utensils-cookware",
    subcategory_id: null,
    description: "Fine wire mesh strainer chhalni for atta, suji and tea straining.",
    image_url: "/images/products/colander-chhalni.svg",
    tags: ["chhalni", "strainer", "colander"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 90,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-chhalni-mesh",
        product_id: "prod-steel-colander-chhalni",
        label: "Stainless Steel Mesh",
        mrp: 90,
        price: 69,
        stock: 40,
        low_stock_threshold: 10,
        sku: "CHHALNI-MESH",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },

  // 11. Miscellaneous & Home Needs
  {
    id: "prod-duracell-aa-batteries-4pcs",
    name: "Duracell Ultra AA Alkaline Batteries (Pack of 4)",
    slug: "duracell-aa-batteries-4pcs",
    brand: "Duracell",
    category_id: "misc-items",
    subcategory_id: null,
    description: "Long lasting 100% power alkaline AA battery cells for clocks and remotes.",
    image_url: "/images/products/duracell-batteries.svg",
    tags: ["batteries", "duracell", "aa", "electrical"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 160,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-duracell-aa4",
        product_id: "prod-duracell-aa-batteries-4pcs",
        label: "Pack of 4",
        mrp: 160,
        price: 140,
        stock: 40,
        low_stock_threshold: 10,
        sku: "DURACELL-AA4",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-wipro-9w-led-bulb",
    name: "Wipro Garnet 9W LED Bulb (Cool Day White)",
    slug: "wipro-9w-led-bulb",
    brand: "Wipro",
    category_id: "misc-items",
    subcategory_id: null,
    description: "Energy saving high lumen 900lm B22 base LED bulb.",
    image_url: "/images/products/led-bulb.svg",
    tags: ["led bulb", "wipro", "bulb", "lighting"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 180,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-wipro-9w",
        product_id: "prod-wipro-9w-led-bulb",
        label: "9W Cool White (B22)",
        mrp: 140,
        price: 99,
        stock: 60,
        low_stock_threshold: 10,
        sku: "WIPRO-9W",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-household-white-candles-12pcs",
    name: "Wax Safety Household Candles (Pack of 12)",
    slug: "household-white-candles-12pcs",
    brand: "Bright Home",
    category_id: "misc-items",
    subcategory_id: null,
    description: "Smokeless white emergency lighting and puja candles.",
    image_url: "/images/products/white-candles.svg",
    tags: ["candles", "mombatti", "lighting"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 140,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-candle-12",
        product_id: "prod-household-white-candles-12pcs",
        label: "Pack of 12",
        mrp: 60,
        price: 48,
        stock: 50,
        low_stock_threshold: 10,
        sku: "CANDLE-12",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-ship-safety-matchboxes-10pk",
    name: "Ship Safety Matchboxes (Bundle of 10 Boxes)",
    slug: "ship-safety-matchboxes-10pk",
    brand: "Ship",
    category_id: "kitchen-essentials",
    subcategory_id: null,
    description: "Carbonized safety matchsticks for kitchen and pooja.",
    image_url: "/images/products/matchboxes.svg",
    tags: ["matchbox", "maachis", "ship"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 320,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-match-10pk",
        product_id: "prod-ship-safety-matchboxes-10pk",
        label: "Bundle of 10 Boxes",
        mrp: 20,
        price: 18,
        stock: 100,
        low_stock_threshold: 20,
        sku: "MATCH-10PK",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-fevicol-mr-glue-100g",
    name: "Fevicol MR Squeezy Bottle Adhesive Glue (100g)",
    slug: "fevicol-mr-glue-100g",
    brand: "Fevicol",
    category_id: "stationery",
    subcategory_id: null,
    description: "Non-staining synthetic craft and paper adhesive glue.",
    image_url: "/images/products/fevicol-glue.svg",
    tags: ["fevicol", "glue", "stationery"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 110,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-fevicol-100g",
        product_id: "prod-fevicol-mr-glue-100g",
        label: "100 g Squeezy",
        mrp: 35,
        price: 30,
        stock: 60,
        low_stock_threshold: 10,
        sku: "FEVICOL-100G",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-craft-kitchen-scissors",
    name: "Multi-Purpose Kitchen & Craft Scissors",
    slug: "craft-kitchen-scissors",
    brand: "Kitchen Craft",
    category_id: "misc-items",
    subcategory_id: null,
    description: "Heavy duty sharp stainless steel grip cutting scissors.",
    image_url: "/images/products/craft-scissors.svg",
    tags: ["scissors", "kainchi", "kitchen tools"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 70,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-scissors-8in",
        product_id: "prod-craft-kitchen-scissors",
        label: "8-inch Stainless Steel",
        mrp: 120,
        price: 89,
        stock: 30,
        low_stock_threshold: 5,
        sku: "SCISSORS-8IN",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-emergency-sewing-needle-kit",
    name: "Home Emergency Tailoring & Sewing Needle Kit",
    slug: "emergency-sewing-needle-kit",
    brand: "Stitch Craft",
    category_id: "misc-items",
    subcategory_id: null,
    description: "Assorted thread spools, needles, buttons and safety pins.",
    image_url: "/images/products/sewing-kit.svg",
    tags: ["sewing kit", "needle", "home emergency"],
    is_featured: false,
    is_popular: false,
    is_active: true,
    sold_count: 55,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-sewing-kit",
        product_id: "prod-emergency-sewing-needle-kit",
        label: "Compact Travel Kit",
        mrp: 80,
        price: 59,
        stock: 40,
        low_stock_threshold: 10,
        sku: "SEWING-KIT",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
  {
    id: "prod-chef-gas-stove-lighter",
    name: "Chef Gas Stove Spark Lighter for Kitchen",
    slug: "chef-gas-stove-lighter",
    brand: "Kitchen Craft",
    category_id: "kitchen-essentials",
    subcategory_id: null,
    description: "Durable stainless steel electronic kitchen gas stove lighter.",
    image_url: "/images/products/gas-lighter.svg",
    tags: ["gas lighter", "lighter", "kitchen"],
    is_featured: false,
    is_popular: true,
    is_active: true,
    sold_count: 135,
    created_at: new Date().toISOString(),
    product_variants: [
      {
        id: "var-gas-lighter",
        product_id: "prod-chef-gas-stove-lighter",
        label: "Electronic Steel Lighter",
        mrp: 75,
        price: 55,
        stock: 50,
        low_stock_threshold: 10,
        sku: "GAS-LIGHTER",
        barcode: null,
        sort_order: 0,
        is_active: true,
      },
    ],
  },
];
