-- ==============================================================================
-- COMPLETE GROCERY CATALOG SEED SCRIPT FOR ARUN GOPAL TRADERS
-- (All 226 Categories + 302 Products & Variants)
-- ==============================================================================

-- PART 1: CORE CATALOG (72 Master Items + All Categories)

REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_order_event() FROM anon, authenticated;

INSERT INTO public.categories (name,slug,icon,image_url,sort_order) VALUES
('Atta & Flour','atta-flour','🌾','/images/atta.jpg',0),
('Rice','rice','🍚','/images/rice.jpg',1),
('Pulses & Dal','pulses-dal','🫘','/images/dal.jpg',2),
('Oil & Ghee','oil-ghee','🛢️','/images/oil.jpg',3),
('Spices & Masala','spices-masala','🌶️','/images/spices.jpg',4),
('Salt & Sugar','salt-sugar','🧂','/images/spices.jpg',5),
('Dry Fruits','dry-fruits','🥜','/images/dryfruits.jpg',6),
('Tea & Coffee','tea-coffee','☕','/images/tea.jpg',7),
('Biscuits','biscuits','🍪','/images/biscuits.jpg',8),
('Namkeen & Snacks','namkeen-snacks','🥨','/images/snacks.jpg',9),
('Chocolates','chocolates','🍫','/images/snacks.jpg',10),
('Noodles & Pasta','noodles-pasta','🍜','/images/packaged.jpg',11),
('Sauces & Spreads','sauces-spreads','🥫','/images/packaged.jpg',12),
('Dairy Products','dairy','🥛','/images/dairy.jpg',13),
('Beverages','beverages','🥤','/images/beverages.jpg',14),
('Packaged Foods','packaged-foods','📦','/images/packaged.jpg',15),
('Breakfast Items','breakfast','🥣','/images/packaged.jpg',16),
('Baby Products','baby-products','🍼','/images/baby.jpg',17),
('Personal Care','personal-care','🧴','/images/personal.jpg',18),
('Hair Care','hair-care','💇','/images/personal.jpg',19),
('Skin Care','skin-care','🧖','/images/personal.jpg',20),
('Oral Care','oral-care','🪥','/images/personal.jpg',21),
('Household Cleaning','household-cleaning','🧽','/images/household.jpg',22),
('Laundry','laundry','🧺','/images/household.jpg',23),
('Kitchen Essentials','kitchen-essentials','🍳','/images/household.jpg',24),
('Pooja Items','pooja-items','🪔','/images/pooja.jpg',25),
('Stationery','stationery','✏️','/images/stationery.jpg',26),
('Pet Supplies','pet-supplies','🐕','/images/packaged.jpg',27),
('Other','other','🛒','/images/packaged.jpg',28);

INSERT INTO public.categories (parent_id,name,slug,sort_order)
SELECT c.id,v.name,v.slug,v.so FROM (VALUES
('atta-flour','Wheat Atta','atta-flour-wheat-atta',0),
('atta-flour','Multigrain Atta','atta-flour-multigrain-atta',1),
('atta-flour','Maida','atta-flour-maida',2),
('atta-flour','Besan','atta-flour-besan',3),
('atta-flour','Suji / Rava','atta-flour-suji-rava',4),
('atta-flour','Rice Flour','atta-flour-rice-flour',5),
('atta-flour','Corn Flour','atta-flour-corn-flour',6),
('atta-flour','Millet Flour','atta-flour-millet-flour',7),
('atta-flour','Sattu','atta-flour-sattu',8),
('rice','Basmati Rice','rice-basmati-rice',0),
('rice','Non-Basmati Rice','rice-non-basmati-rice',1),
('rice','Sella Rice','rice-sella-rice',2),
('rice','Broken Rice','rice-broken-rice',3),
('rice','Brown Rice','rice-brown-rice',4),
('rice','Local Rice','rice-local-rice',5),
('pulses-dal','Toor Dal','pulses-dal-toor-dal',0),
('pulses-dal','Moong Dal','pulses-dal-moong-dal',1),
('pulses-dal','Masoor Dal','pulses-dal-masoor-dal',2),
('pulses-dal','Chana Dal','pulses-dal-chana-dal',3),
('pulses-dal','Urad Dal','pulses-dal-urad-dal',4),
('pulses-dal','Rajma','pulses-dal-rajma',5),
('pulses-dal','Kabuli Chana','pulses-dal-kabuli-chana',6),
('pulses-dal','Black Chana','pulses-dal-black-chana',7),
('pulses-dal','Lobia','pulses-dal-lobia',8),
('pulses-dal','Matar','pulses-dal-matar',9),
('oil-ghee','Mustard Oil','oil-ghee-mustard-oil',0),
('oil-ghee','Sunflower Oil','oil-ghee-sunflower-oil',1),
('oil-ghee','Soybean Oil','oil-ghee-soybean-oil',2),
('oil-ghee','Groundnut Oil','oil-ghee-groundnut-oil',3),
('oil-ghee','Rice Bran Oil','oil-ghee-rice-bran-oil',4),
('oil-ghee','Coconut Oil','oil-ghee-coconut-oil',5),
('oil-ghee','Olive Oil','oil-ghee-olive-oil',6),
('oil-ghee','Desi Ghee','oil-ghee-desi-ghee',7),
('oil-ghee','Vanaspati','oil-ghee-vanaspati',8),
('spices-masala','Turmeric','spices-masala-turmeric',0),
('spices-masala','Red Chilli','spices-masala-red-chilli',1),
('spices-masala','Coriander Powder','spices-masala-coriander-powder',2),
('spices-masala','Garam Masala','spices-masala-garam-masala',3),
('spices-masala','Chaat Masala','spices-masala-chaat-masala',4),
('spices-masala','Cumin','spices-masala-cumin',5),
('spices-masala','Black Pepper','spices-masala-black-pepper',6),
('spices-masala','Cardamom','spices-masala-cardamom',7),
('spices-masala','Cloves','spices-masala-cloves',8),
('spices-masala','Cinnamon','spices-masala-cinnamon',9),
('spices-masala','Bay Leaf','spices-masala-bay-leaf',10),
('spices-masala','Hing','spices-masala-hing',11),
('spices-masala','Mustard Seeds','spices-masala-mustard-seeds',12),
('spices-masala','Fennel','spices-masala-fennel',13),
('spices-masala','Ajwain','spices-masala-ajwain',14),
('spices-masala','Methi','spices-masala-methi',15),
('spices-masala','Whole Spices','spices-masala-whole-spices',16),
('spices-masala','Mixed Masala','spices-masala-mixed-masala',17),
('salt-sugar','Sugar','salt-sugar-sugar',0),
('salt-sugar','Brown Sugar','salt-sugar-brown-sugar',1),
('salt-sugar','Iodized Salt','salt-sugar-iodized-salt',2),
('salt-sugar','Rock Salt','salt-sugar-rock-salt',3),
('salt-sugar','Black Salt','salt-sugar-black-salt',4),
('salt-sugar','Jaggery','salt-sugar-jaggery',5),
('salt-sugar','Honey','salt-sugar-honey',6),
('dry-fruits','Almonds','dry-fruits-almonds',0),
('dry-fruits','Cashews','dry-fruits-cashews',1),
('dry-fruits','Raisins','dry-fruits-raisins',2),
('dry-fruits','Walnuts','dry-fruits-walnuts',3),
('dry-fruits','Pistachios','dry-fruits-pistachios',4),
('dry-fruits','Dates','dry-fruits-dates',5),
('dry-fruits','Mixed Dry Fruits','dry-fruits-mixed-dry-fruits',6),
('dry-fruits','Seeds','dry-fruits-seeds',7),
('tea-coffee','Tea','tea-coffee-tea',0),
('tea-coffee','Green Tea','tea-coffee-green-tea',1),
('tea-coffee','Black Tea','tea-coffee-black-tea',2),
('tea-coffee','Instant Coffee','tea-coffee-instant-coffee',3),
('tea-coffee','Coffee Powder','tea-coffee-coffee-powder',4),
('tea-coffee','Milk Powder','tea-coffee-milk-powder',5),
('biscuits','Glucose Biscuits','biscuits-glucose-biscuits',0),
('biscuits','Cream Biscuits','biscuits-cream-biscuits',1),
('biscuits','Marie','biscuits-marie',2),
('biscuits','Cookies','biscuits-cookies',3),
('biscuits','Crackers','biscuits-crackers',4),
('biscuits','Rusk','biscuits-rusk',5),
('namkeen-snacks','Bhujia','namkeen-snacks-bhujia',0),
('namkeen-snacks','Mixture','namkeen-snacks-mixture',1),
('namkeen-snacks','Chips','namkeen-snacks-chips',2),
('namkeen-snacks','Kurkure','namkeen-snacks-kurkure',3),
('namkeen-snacks','Popcorn','namkeen-snacks-popcorn',4),
('namkeen-snacks','Peanuts','namkeen-snacks-peanuts',5),
('namkeen-snacks','Roasted Chana','namkeen-snacks-roasted-chana',6),
('namkeen-snacks','Fryums','namkeen-snacks-fryums',7),
('chocolates','Chocolates','chocolates-chocolates',0),
('chocolates','Toffees','chocolates-toffees',1),
('chocolates','Candies','chocolates-candies',2),
('chocolates','Lollipops','chocolates-lollipops',3),
('chocolates','Wafers','chocolates-wafers',4),
('chocolates','Chewing Gum','chocolates-chewing-gum',5),
('noodles-pasta','Noodles','noodles-pasta-noodles',0),
('noodles-pasta','Pasta','noodles-pasta-pasta',1),
('noodles-pasta','Vermicelli','noodles-pasta-vermicelli',2),
('noodles-pasta','Instant Soup','noodles-pasta-instant-soup',3),
('noodles-pasta','Ready to Eat','noodles-pasta-ready-to-eat',4),
('sauces-spreads','Tomato Ketchup','sauces-spreads-tomato-ketchup',0),
('sauces-spreads','Chilli Sauce','sauces-spreads-chilli-sauce',1),
('sauces-spreads','Soy Sauce','sauces-spreads-soy-sauce',2),
('sauces-spreads','Mayonnaise','sauces-spreads-mayonnaise',3),
('sauces-spreads','Jam','sauces-spreads-jam',4),
('sauces-spreads','Peanut Butter','sauces-spreads-peanut-butter',5),
('sauces-spreads','Pickles','sauces-spreads-pickles',6),
('sauces-spreads','Chutneys','sauces-spreads-chutneys',7),
('dairy','Milk','dairy-milk',0),
('dairy','Curd','dairy-curd',1),
('dairy','Paneer','dairy-paneer',2),
('dairy','Butter','dairy-butter',3),
('dairy','Cheese','dairy-cheese',4),
('dairy','Cream','dairy-cream',5),
('dairy','Flavoured Milk','dairy-flavoured-milk',6),
('dairy','Lassi','dairy-lassi',7),
('beverages','Mineral Water','beverages-mineral-water',0),
('beverages','Soft Drinks','beverages-soft-drinks',1),
('beverages','Juice','beverages-juice',2),
('beverages','Energy Drinks','beverages-energy-drinks',3),
('beverages','Soda','beverages-soda',4),
('beverages','Sharbat','beverages-sharbat',5),
('beverages','Glucose Drinks','beverages-glucose-drinks',6),
('packaged-foods','Poha','packaged-foods-poha',0),
('packaged-foods','Oats','packaged-foods-oats',1),
('packaged-foods','Cornflakes','packaged-foods-cornflakes',2),
('packaged-foods','Breakfast Cereals','packaged-foods-breakfast-cereals',3),
('packaged-foods','Ready Meals','packaged-foods-ready-meals',4),
('breakfast','Bread','breakfast-bread',0),
('breakfast','Buns','breakfast-buns',1),
('breakfast','Cakes','breakfast-cakes',2),
('breakfast','Toast','breakfast-toast',3),
('breakfast','Cereals','breakfast-cereals',4),
('baby-products','Baby Soap','baby-products-baby-soap',0),
('baby-products','Baby Shampoo','baby-products-baby-shampoo',1),
('baby-products','Baby Powder','baby-products-baby-powder',2),
('baby-products','Baby Oil','baby-products-baby-oil',3),
('baby-products','Diapers','baby-products-diapers',4),
('baby-products','Baby Food','baby-products-baby-food',5),
('baby-products','Baby Wipes','baby-products-baby-wipes',6),
('personal-care','Soap','personal-care-soap',0),
('personal-care','Face Wash','personal-care-face-wash',1),
('personal-care','Body Lotion','personal-care-body-lotion',2),
('personal-care','Deodorant','personal-care-deodorant',3),
('personal-care','Perfume','personal-care-perfume',4),
('personal-care','Talcum Powder','personal-care-talcum-powder',5),
('personal-care','Hand Wash','personal-care-hand-wash',6),
('hair-care','Shampoo','hair-care-shampoo',0),
('hair-care','Hair Oil','hair-care-hair-oil',1),
('hair-care','Conditioner','hair-care-conditioner',2),
('hair-care','Hair Serum','hair-care-hair-serum',3),
('hair-care','Hair Colour','hair-care-hair-colour',4),
('skin-care','Moisturizer','skin-care-moisturizer',0),
('skin-care','Sunscreen','skin-care-sunscreen',1),
('skin-care','Cold Cream','skin-care-cold-cream',2),
('skin-care','Face Cream','skin-care-face-cream',3),
('oral-care','Toothpaste','oral-care-toothpaste',0),
('oral-care','Toothbrush','oral-care-toothbrush',1),
('oral-care','Mouthwash','oral-care-mouthwash',2),
('oral-care','Dental Floss','oral-care-dental-floss',3),
('household-cleaning','Floor Cleaner','household-cleaning-floor-cleaner',0),
('household-cleaning','Toilet Cleaner','household-cleaning-toilet-cleaner',1),
('household-cleaning','Dishwash','household-cleaning-dishwash',2),
('household-cleaning','Glass Cleaner','household-cleaning-glass-cleaner',3),
('household-cleaning','Disinfectant','household-cleaning-disinfectant',4),
('household-cleaning','Phenyl','household-cleaning-phenyl',5),
('household-cleaning','Bleach','household-cleaning-bleach',6),
('laundry','Detergent Powder','laundry-detergent-powder',0),
('laundry','Detergent Liquid','laundry-detergent-liquid',1),
('laundry','Detergent Bar','laundry-detergent-bar',2),
('laundry','Fabric Conditioner','laundry-fabric-conditioner',3),
('laundry','Stain Remover','laundry-stain-remover',4),
('kitchen-essentials','Aluminium Foil','kitchen-essentials-aluminium-foil',0),
('kitchen-essentials','Cling Film','kitchen-essentials-cling-film',1),
('kitchen-essentials','Garbage Bags','kitchen-essentials-garbage-bags',2),
('kitchen-essentials','Scrubbers','kitchen-essentials-scrubbers',3),
('kitchen-essentials','Sponges','kitchen-essentials-sponges',4),
('kitchen-essentials','Matchbox','kitchen-essentials-matchbox',5),
('kitchen-essentials','Lighters','kitchen-essentials-lighters',6),
('pooja-items','Agarbatti','pooja-items-agarbatti',0),
('pooja-items','Dhoop','pooja-items-dhoop',1),
('pooja-items','Camphor','pooja-items-camphor',2),
('pooja-items','Cotton Wicks','pooja-items-cotton-wicks',3),
('pooja-items','Diya','pooja-items-diya',4),
('pooja-items','Pooja Oil','pooja-items-pooja-oil',5),
('pooja-items','Kumkum','pooja-items-kumkum',6),
('pooja-items','Roli','pooja-items-roli',7),
('pooja-items','Pooja Samagri','pooja-items-pooja-samagri',8),
('stationery','Pens','stationery-pens',0),
('stationery','Pencils','stationery-pencils',1),
('stationery','Erasers','stationery-erasers',2),
('stationery','Notebooks','stationery-notebooks',3),
('stationery','Registers','stationery-registers',4),
('stationery','Glue','stationery-glue',5),
('stationery','Tape','stationery-tape',6),
('stationery','Markers','stationery-markers',7),
('pet-supplies','Pet Food','pet-supplies-pet-food',0),
('pet-supplies','Pet Treats','pet-supplies-pet-treats',1),
('pet-supplies','Pet Care','pet-supplies-pet-care',2)
) AS v(pslug,name,slug,so) JOIN public.categories c ON c.slug=v.pslug;

INSERT INTO public.products (name,slug,brand,category_id,subcategory_id,description,image_url,tags,is_featured,is_popular)
SELECT v.name,v.slug,v.brand,c.id,sc.id,v.descr,v.img,v.tags,v.feat,v.pop FROM (VALUES
('Fortune Chakki Fresh Atta','fortune-chakki-fresh-atta','Fortune','atta-flour','Wheat Atta','100% whole wheat chakki atta for soft, fluffy rotis.','/images/atta.jpg',ARRAY['atta','wheat','flour'],true,true),
('Aashirvaad Shudh Chakki Atta','aashirvaad-shudh-chakki-atta','Aashirvaad','atta-flour','Wheat Atta','Made from 100% MP wheat, sieved twice for perfect rotis.','/images/atta.jpg',ARRAY['atta','wheat'],true,true),
('Rajdhani Besan','rajdhani-besan','Rajdhani','atta-flour','Besan','Fine gram flour, ideal for pakoda, kadhi and sweets.','/images/atta.jpg',ARRAY['besan','gram flour'],false,true),
('Bansi Suji / Rava','bansi-suji-rava','Bansi','atta-flour','Suji / Rava','Coarse semolina for halwa, upma and idli.','/images/atta.jpg',ARRAY['suji','rava'],false,false),
('Shakti Bhog Maida','shakti-bhog-maida','Shakti Bhog','atta-flour','Maida','Refined flour for puri, naan and bakery use.','/images/atta.jpg',ARRAY['maida'],false,false),
('India Gate Classic Basmati Rice','india-gate-classic-basmati-rice','India Gate','rice','Basmati Rice','Long grain aged basmati with rich aroma.','/images/rice.jpg',ARRAY['rice','basmati'],true,true),
('Daawat Rozana Gold Basmati','daawat-rozana-gold-basmati','Daawat','rice','Basmati Rice','Everyday basmati rice, fluffy and non-sticky.','/images/rice.jpg',ARRAY['rice','basmati'],false,true),
('Sona Masoori Rice (Local)','sona-masoori-rice-local','Local','rice','Non-Basmati Rice','Light and easy to digest daily rice.','/images/rice.jpg',ARRAY['rice','sona masoori'],false,false),
('Tata Sampann Toor Dal','tata-sampann-toor-dal','Tata Sampann','pulses-dal','Toor Dal','Unpolished toor dal, rich in protein.','/images/dal.jpg',ARRAY['dal','toor','arhar'],true,true),
('Moong Dal Dhuli','moong-dal-dhuli','Local','pulses-dal','Moong Dal','Split washed moong dal, cooks fast.','/images/dal.jpg',ARRAY['dal','moong'],false,true),
('Masoor Dal','masoor-dal','Local','pulses-dal','Masoor Dal','Everyday red lentils.','/images/dal.jpg',ARRAY['dal','masoor'],false,false),
('Rajma Chitra','rajma-chitra','Local','pulses-dal','Rajma','Premium chitra rajma kidney beans.','/images/dal.jpg',ARRAY['rajma'],false,false),
('Kabuli Chana','kabuli-chana','Local','pulses-dal','Kabuli Chana','Big size white chana for chole.','/images/dal.jpg',ARRAY['chana','chole'],false,false),
('Fortune Kachi Ghani Mustard Oil','fortune-kachi-ghani-mustard-oil','Fortune','oil-ghee','Mustard Oil','Cold pressed kachi ghani mustard oil.','/images/oil.jpg',ARRAY['oil','mustard','sarso'],true,true),
('Patanjali Kachi Ghani Sarson Tel','patanjali-kachi-ghani-sarson-tel','Patanjali','oil-ghee','Mustard Oil','Pure mustard oil with strong aroma.','/images/oil.jpg',ARRAY['oil','mustard'],false,true),
('Fortune Sunlite Refined Sunflower Oil','fortune-sunlite-refined-sunflower-oil','Fortune','oil-ghee','Sunflower Oil','Light and healthy refined sunflower oil.','/images/oil.jpg',ARRAY['oil','sunflower'],false,true),
('Amul Pure Desi Ghee','amul-pure-desi-ghee','Amul','oil-ghee','Desi Ghee','Made from cow milk, rich aroma and taste.','/images/oil.jpg',ARRAY['ghee','amul'],true,true),
('Everest Turmeric Powder (Haldi)','everest-turmeric-powder-haldi','Everest','spices-masala','Turmeric','Bright colour, pure haldi powder.','/images/spices.jpg',ARRAY['haldi','turmeric','masala'],false,true),
('MDH Deggi Mirch','mdh-deggi-mirch','MDH','spices-masala','Red Chilli','Rich red colour with mild heat.','/images/spices.jpg',ARRAY['mirch','chilli'],false,false),
('Everest Garam Masala','everest-garam-masala','Everest','spices-masala','Garam Masala','Classic blend of whole spices.','/images/spices.jpg',ARRAY['garam masala'],false,true),
('Catch Jeera Whole','catch-jeera-whole','Catch','spices-masala','Cumin','Aromatic whole cumin seeds.','/images/spices.jpg',ARRAY['jeera','cumin'],false,false),
('Everest Dhaniya Powder','everest-dhaniya-powder','Everest','spices-masala','Coriander Powder','Fresh ground coriander powder.','/images/spices.jpg',ARRAY['dhaniya','coriander'],false,false),
('Tata Salt Iodised','tata-salt-iodised','Tata','salt-sugar','Iodized Salt','Desh ka namak - vacuum evaporated iodised salt.','/images/spices.jpg',ARRAY['salt','namak'],true,true),
('Madhur Pure Sugar','madhur-pure-sugar','Madhur','salt-sugar','Sugar','Sparkling white refined sugar.','/images/spices.jpg',ARRAY['sugar','cheeni'],false,true),
('Organic Gud (Jaggery) Block','organic-gud-jaggery-block','Local','salt-sugar','Jaggery','Chemical-free jaggery from local mill.','/images/spices.jpg',ARRAY['gud','jaggery'],false,false),
('Dabur Honey','dabur-honey','Dabur','salt-sugar','Honey','100% pure honey, no sugar added.','/images/spices.jpg',ARRAY['honey','shahad'],false,false),
('California Almonds (Badam)','california-almonds-badam','Premium','dry-fruits','Almonds','Crunchy premium California almonds.','/images/dryfruits.jpg',ARRAY['badam','almond','dry fruit'],true,true),
('Whole Cashew W320 (Kaju)','whole-cashew-w320-kaju','Premium','dry-fruits','Cashews','Grade W320 whole cashew nuts.','/images/dryfruits.jpg',ARRAY['kaju','cashew'],false,true),
('Kishmish (Raisins)','kishmish-raisins','Premium','dry-fruits','Raisins','Seedless golden raisins.','/images/dryfruits.jpg',ARRAY['kishmish','raisin'],false,false),
('Tata Tea Premium','tata-tea-premium','Tata Tea','tea-coffee','Tea','Strong, refreshing Assam blend.','/images/tea.jpg',ARRAY['chai','tea'],true,true),
('Red Label Natural Care Tea','red-label-natural-care-tea','Brooke Bond','tea-coffee','Tea','Tea with 5 ayurvedic ingredients.','/images/tea.jpg',ARRAY['chai','tea'],false,true),
('Nescafe Classic Instant Coffee','nescafe-classic-instant-coffee','Nescafe','tea-coffee','Instant Coffee','100% pure instant coffee.','/images/tea.jpg',ARRAY['coffee'],false,false),
('Parle-G Original Glucose Biscuits','parle-g-original-glucose-biscuits','Parle','biscuits','Glucose Biscuits','India''s favourite glucose biscuit.','/images/biscuits.jpg',ARRAY['biscuit','parle-g'],false,true),
('Britannia Good Day Cashew Cookies','britannia-good-day-cashew-cookies','Britannia','biscuits','Cookies','Buttery cookies loaded with cashew.','/images/biscuits.jpg',ARRAY['biscuit','cookies'],false,true),
('Sunfeast Marie Light','sunfeast-marie-light','Sunfeast','biscuits','Marie','Light tea-time marie biscuits.','/images/biscuits.jpg',ARRAY['biscuit','marie'],false,false),
('Haldiram''s Aloo Bhujia','haldiram-s-aloo-bhujia','Haldiram''s','namkeen-snacks','Bhujia','Crispy spicy potato bhujia.','/images/snacks.jpg',ARRAY['namkeen','bhujia'],true,true),
('Bikaji Bikaneri Bhujia','bikaji-bikaneri-bhujia','Bikaji','namkeen-snacks','Bhujia','Authentic Bikaneri bhujia.','/images/snacks.jpg',ARRAY['namkeen'],false,false),
('Lay''s India''s Magic Masala','lay-s-india-s-magic-masala','Lay''s','namkeen-snacks','Chips','Crunchy potato chips with masala.','/images/snacks.jpg',ARRAY['chips','snacks'],false,true),
('Cadbury Dairy Milk','cadbury-dairy-milk','Cadbury','chocolates','Chocolates','Smooth creamy milk chocolate.','/images/snacks.jpg',ARRAY['chocolate'],false,true),
('Maggi 2-Minute Masala Noodles','maggi-2-minute-masala-noodles','Maggi','noodles-pasta','Noodles','Everyone''s favourite instant noodles.','/images/packaged.jpg',ARRAY['maggi','noodles'],true,true),
('Sunfeast Yippee Pasta Masala','sunfeast-yippee-pasta-masala','Sunfeast','noodles-pasta','Pasta','Instant pasta with masala mix.','/images/packaged.jpg',ARRAY['pasta'],false,false),
('Kissan Fresh Tomato Ketchup','kissan-fresh-tomato-ketchup','Kissan','sauces-spreads','Tomato Ketchup','Made from 100% real tomatoes.','/images/packaged.jpg',ARRAY['ketchup','sauce'],false,true),
('Mother''s Recipe Mango Pickle','mother-s-recipe-mango-pickle','Mother''s Recipe','sauces-spreads','Pickles','Traditional mango achar.','/images/packaged.jpg',ARRAY['pickle','achar'],false,false),
('Amul Taaza Toned Milk','amul-taaza-toned-milk','Amul','dairy','Milk','Homogenised toned milk, tetra pack.','/images/dairy.jpg',ARRAY['milk','dudh'],false,true),
('Amul Butter','amul-butter','Amul','dairy','Butter','Utterly butterly delicious.','/images/dairy.jpg',ARRAY['butter'],false,true),
('Bisleri Mineral Water','bisleri-mineral-water','Bisleri','beverages','Mineral Water','Packaged drinking water.','/images/beverages.jpg',ARRAY['water'],false,false),
('Coca-Cola Soft Drink','coca-cola-soft-drink','Coca-Cola','beverages','Soft Drinks','Chilled refreshment.','/images/beverages.jpg',ARRAY['cold drink'],false,false),
('Real Mixed Fruit Juice','real-mixed-fruit-juice','Real','beverages','Juice','No preservatives fruit juice.','/images/beverages.jpg',ARRAY['juice'],false,false),
('Kellogg''s Corn Flakes','kellogg-s-corn-flakes','Kellogg''s','packaged-foods','Cornflakes','Crispy golden flakes of corn.','/images/packaged.jpg',ARRAY['cornflakes','breakfast'],false,false),
('Aashirvaad Poha','aashirvaad-poha','Aashirvaad','packaged-foods','Poha','Thick flattened rice for breakfast.','/images/packaged.jpg',ARRAY['poha'],false,false),
('Saffola Oats','saffola-oats','Saffola','packaged-foods','Oats','100% natural wholegrain oats.','/images/packaged.jpg',ARRAY['oats'],false,false),
('Johnson''s Baby Powder','johnson-s-baby-powder','Johnson''s','baby-products','Baby Powder','Gentle powder for baby''s soft skin.','/images/baby.jpg',ARRAY['baby'],false,false),
('Pampers Baby Dry Pants','pampers-baby-dry-pants','Pampers','baby-products','Diapers','Up to 12 hours dryness.','/images/baby.jpg',ARRAY['diaper','baby'],false,true),
('Lifebuoy Total 10 Soap','lifebuoy-total-10-soap','Lifebuoy','personal-care','Soap','Germ protection bathing soap.','/images/personal.jpg',ARRAY['soap'],false,true),
('Dettol Handwash Refill','dettol-handwash-refill','Dettol','personal-care','Hand Wash','Kills 99.9% germs.','/images/personal.jpg',ARRAY['handwash'],false,false),
('Parachute Coconut Hair Oil','parachute-coconut-hair-oil','Parachute','hair-care','Hair Oil','100% pure coconut oil.','/images/personal.jpg',ARRAY['hair oil','coconut'],false,true),
('Clinic Plus Strong & Long Shampoo','clinic-plus-strong-long-shampoo','Clinic Plus','hair-care','Shampoo','Milk protein shampoo for strong hair.','/images/personal.jpg',ARRAY['shampoo'],false,false),
('Nivea Soft Light Moisturiser','nivea-soft-light-moisturiser','Nivea','skin-care','Moisturizer','Light non-greasy moisturiser.','/images/personal.jpg',ARRAY['cream','skin'],false,false),
('Colgate Strong Teeth Toothpaste','colgate-strong-teeth-toothpaste','Colgate','oral-care','Toothpaste','Calcium boost for strong teeth.','/images/personal.jpg',ARRAY['toothpaste'],false,true),
('Lizol Disinfectant Floor Cleaner','lizol-disinfectant-floor-cleaner','Lizol','household-cleaning','Floor Cleaner','Kills 99.9% germs, citrus fragrance.','/images/household.jpg',ARRAY['floor cleaner'],false,true),
('Harpic Power Plus Toilet Cleaner','harpic-power-plus-toilet-cleaner','Harpic','household-cleaning','Toilet Cleaner','Thick liquid, 10x better cleaning.','/images/household.jpg',ARRAY['toilet cleaner'],false,false),
('Vim Dishwash Bar','vim-dishwash-bar','Vim','household-cleaning','Dishwash','Lemon power on tough grease.','/images/household.jpg',ARRAY['dishwash'],false,false),
('Surf Excel Easy Wash Detergent Powder','surf-excel-easy-wash-detergent-powder','Surf Excel','laundry','Detergent Powder','Removes tough stains easily.','/images/household.jpg',ARRAY['detergent','surf'],true,true),
('Rin Detergent Bar','rin-detergent-bar','Rin','laundry','Detergent Bar','Powerful whiteness bar.','/images/household.jpg',ARRAY['detergent'],false,false),
('Comfort Fabric Conditioner','comfort-fabric-conditioner','Comfort','laundry','Fabric Conditioner','Softness and long lasting fragrance.','/images/household.jpg',ARRAY['fabric'],false,false),
('Scotch-Brite Scrub Pad','scotch-brite-scrub-pad','Scotch-Brite','kitchen-essentials','Scrubbers','Tough on grease, easy on hands.','/images/household.jpg',ARRAY['scrub'],false,false),
('Homefoil Aluminium Foil','homefoil-aluminium-foil','Homefoil','kitchen-essentials','Aluminium Foil','Keeps food fresh and warm.','/images/household.jpg',ARRAY['foil'],false,false),
('Cycle Pure Agarbatti Three-in-One','cycle-pure-agarbatti-three-in-one','Cycle','pooja-items','Agarbatti','Classic fragrance incense sticks.','/images/pooja.jpg',ARRAY['agarbatti','pooja'],false,true),
('Mangaldeep Camphor (Kapoor)','mangaldeep-camphor-kapoor','Mangaldeep','pooja-items','Camphor','Pure camphor tablets for aarti.','/images/pooja.jpg',ARRAY['kapoor','pooja'],false,false),
('Classmate Notebook 172 Pages','classmate-notebook-172-pages','Classmate','stationery','Notebooks','Single line ruled notebook.','/images/stationery.jpg',ARRAY['notebook','copy'],false,false),
('Cello Butterflow Ball Pen','cello-butterflow-ball-pen','Cello','stationery','Pens','Smooth writing blue ball pen.','/images/stationery.jpg',ARRAY['pen'],false,false),
('Pedigree Adult Dog Food Chicken','pedigree-adult-dog-food-chicken','Pedigree','pet-supplies','Pet Food','Complete nutrition for adult dogs.','/images/packaged.jpg',ARRAY['dog food'],false,false)
) AS v(name,slug,brand,cslug,subname,descr,img,tags,feat,pop)
JOIN public.categories c ON c.slug=v.cslug
LEFT JOIN public.categories sc ON sc.parent_id=c.id AND sc.name=v.subname;

INSERT INTO public.product_variants (product_id,label,mrp,price,stock,sku,sort_order)
SELECT p.id,v.label,v.mrp,v.price,v.stock,v.sku,v.so FROM (VALUES
('fortune-chakki-fresh-atta','5 kg',300,275,40,'FORTUNE-5KG',0),
('fortune-chakki-fresh-atta','10 kg',580,529,18,'FORTUNE-10KG',1),
('aashirvaad-shudh-chakki-atta','5 kg',320,295,32,'AASHIRVAAD-5KG',0),
('aashirvaad-shudh-chakki-atta','10 kg',620,575,12,'AASHIRVAAD-10KG',1),
('rajdhani-besan','500 g',70,62,45,'RAJDHANI-500G',0),
('rajdhani-besan','1 kg',135,119,25,'RAJDHANI-1KG',1),
('bansi-suji-rava','500 g',42,36,50,'BANSISUJI-500G',0),
('bansi-suji-rava','1 kg',80,69,30,'BANSISUJI-1KG',1),
('shakti-bhog-maida','500 g',38,33,40,'SHAKTIMAIDA-500G',0),
('shakti-bhog-maida','1 kg',72,64,22,'SHAKTIMAIDA-1KG',1),
('india-gate-classic-basmati-rice','1 kg',165,148,35,'INDIAGATE-1KG',0),
('india-gate-classic-basmati-rice','5 kg',790,725,14,'INDIAGATE-5KG',1),
('daawat-rozana-gold-basmati','1 kg',120,105,40,'DAAWAT-1KG',0),
('daawat-rozana-gold-basmati','5 kg',560,515,16,'DAAWAT-5KG',1),
('sona-masoori-rice-local','5 kg',320,289,28,'SONAMASOORI-5KG',0),
('sona-masoori-rice-local','10 kg',620,569,10,'SONAMASOORI-10KG',1),
('tata-sampann-toor-dal','500 g',95,86,50,'TOORDAL-500G',0),
('tata-sampann-toor-dal','1 kg',180,165,30,'TOORDAL-1KG',1),
('moong-dal-dhuli','500 g',85,76,45,'MOONGDAL-500G',0),
('moong-dal-dhuli','1 kg',165,148,22,'MOONGDAL-1KG',1),
('masoor-dal','500 g',70,62,48,'MASOORDAL-500G',0),
('masoor-dal','1 kg',135,122,26,'MASOORDAL-1KG',1),
('rajma-chitra','500 g',95,88,30,'RAJMA-500G',0),
('rajma-chitra','1 kg',185,172,15,'RAJMA-1KG',1),
('kabuli-chana','500 g',80,72,35,'KABULI-500G',0),
('kabuli-chana','1 kg',155,142,20,'KABULI-1KG',1),
('fortune-kachi-ghani-mustard-oil','1 L',175,159,40,'FORTMUST-1L',0),
('fortune-kachi-ghani-mustard-oil','2 L',345,315,20,'FORTMUST-2L',1),
('fortune-kachi-ghani-mustard-oil','5 L',850,789,10,'FORTMUST-5L',2),
('patanjali-kachi-ghani-sarson-tel','1 L',180,165,25,'PATSARSON-1L',0),
('patanjali-kachi-ghani-sarson-tel','5 L',880,819,8,'PATSARSON-5L',1),
('fortune-sunlite-refined-sunflower-oil','1 L',155,139,30,'FORTSUN-1L',0),
('fortune-sunlite-refined-sunflower-oil','5 L',760,699,12,'FORTSUN-5L',1),
('amul-pure-desi-ghee','500 ml',340,315,22,'AMULGHEE-500ML',0),
('amul-pure-desi-ghee','1 L',660,619,10,'AMULGHEE-1L',1),
('everest-turmeric-powder-haldi','100 g',38,34,60,'HALDI-100G',0),
('everest-turmeric-powder-haldi','200 g',72,64,35,'HALDI-200G',1),
('everest-turmeric-powder-haldi','500 g',170,155,15,'HALDI-500G',2),
('mdh-deggi-mirch','100 g',95,86,30,'DEGGI-100G',0),
('mdh-deggi-mirch','500 g',430,398,8,'DEGGI-500G',1),
('everest-garam-masala','50 g',55,49,40,'GARAM-50G',0),
('everest-garam-masala','100 g',105,94,25,'GARAM-100G',1),
('catch-jeera-whole','100 g',65,58,35,'JEERA-100G',0),
('catch-jeera-whole','200 g',125,112,18,'JEERA-200G',1),
('everest-dhaniya-powder','100 g',42,37,45,'DHANIYA-100G',0),
('everest-dhaniya-powder','500 g',190,172,12,'DHANIYA-500G',1),
('tata-salt-iodised','500 g',14,12,80,'TATASALT-500G',0),
('tata-salt-iodised','1 kg',28,25,60,'TATASALT-1KG',1),
('madhur-pure-sugar','1 kg',52,46,50,'SUGAR-1KG',0),
('madhur-pure-sugar','5 kg',255,232,15,'SUGAR-5KG',1),
('organic-gud-jaggery-block','500 g',50,44,30,'GUD-500G',0),
('organic-gud-jaggery-block','1 kg',95,85,20,'GUD-1KG',1),
('dabur-honey','250 g',165,149,25,'HONEY-250G',0),
('dabur-honey','500 g',320,289,12,'HONEY-500G',1),
('california-almonds-badam','250 g',290,265,20,'BADAM-250G',0),
('california-almonds-badam','500 g',560,519,10,'BADAM-500G',1),
('california-almonds-badam','1 kg',1090,999,5,'BADAM-1KG',2),
('whole-cashew-w320-kaju','250 g',310,285,15,'KAJU-250G',0),
('whole-cashew-w320-kaju','500 g',610,565,8,'KAJU-500G',1),
('kishmish-raisins','250 g',110,98,25,'KISHMISH-250G',0),
('kishmish-raisins','500 g',210,189,12,'KISHMISH-500G',1),
('tata-tea-premium','250 g',145,132,40,'TATATEA-250G',0),
('tata-tea-premium','500 g',285,259,20,'TATATEA-500G',1),
('tata-tea-premium','1 kg',560,519,8,'TATATEA-1KG',2),
('red-label-natural-care-tea','250 g',150,138,30,'REDLABEL-250G',0),
('red-label-natural-care-tea','500 g',295,272,14,'REDLABEL-500G',1),
('nescafe-classic-instant-coffee','50 g',180,165,20,'NESCAFE-50G',0),
('nescafe-classic-instant-coffee','100 g',340,309,10,'NESCAFE-100G',1),
('parle-g-original-glucose-biscuits','Rs.10 pack',10,10,100,'PARLEG-10',0),
('parle-g-original-glucose-biscuits','800 g Family',90,84,25,'PARLEG-800G',1),
('britannia-good-day-cashew-cookies','100 g',30,27,60,'GOODDAY-100G',0),
('britannia-good-day-cashew-cookies','600 g',150,139,18,'GOODDAY-600G',1),
('sunfeast-marie-light','250 g',40,36,45,'MARIE-250G',0),
('haldiram-s-aloo-bhujia','200 g',55,50,50,'BHUJIA-200G',0),
('haldiram-s-aloo-bhujia','400 g',105,95,25,'BHUJIA-400G',1),
('bikaji-bikaneri-bhujia','200 g',52,47,40,'BIKAJI-200G',0),
('bikaji-bikaneri-bhujia','400 g',100,92,20,'BIKAJI-400G',1),
('lay-s-india-s-magic-masala','Rs.20 pack',20,20,80,'LAYS-20',0),
('lay-s-india-s-magic-masala','Rs.50 pack',50,48,40,'LAYS-50',1),
('cadbury-dairy-milk','13.2 g',10,10,100,'DAIRYMILK-13G',0),
('cadbury-dairy-milk','50 g',45,42,50,'DAIRYMILK-50G',1),
('maggi-2-minute-masala-noodles','70 g single',14,13,120,'MAGGI-70G',0),
('maggi-2-minute-masala-noodles','4 pack',56,52,60,'MAGGI-4PK',1),
('maggi-2-minute-masala-noodles','12 pack',168,155,20,'MAGGI-12PK',2),
('sunfeast-yippee-pasta-masala','70 g',30,27,40,'YIPPEE-70G',0),
('kissan-fresh-tomato-ketchup','500 g',110,99,30,'KISSAN-500G',0),
('kissan-fresh-tomato-ketchup','950 g',180,165,15,'KISSAN-950G',1),
('mother-s-recipe-mango-pickle','400 g',95,86,25,'ACHAR-400G',0),
('amul-taaza-toned-milk','500 ml',29,28,60,'AMULMILK-500ML',0),
('amul-taaza-toned-milk','1 L',75,72,30,'AMULMILK-1L',1),
('amul-butter','100 g',58,55,40,'AMULBUTTER-100G',0),
('amul-butter','500 g',275,265,15,'AMULBUTTER-500G',1),
('bisleri-mineral-water','1 L',20,19,60,'BISLERI-1L',0),
('bisleri-mineral-water','2 L',35,32,30,'BISLERI-2L',1),
('coca-cola-soft-drink','750 ml',45,42,40,'COKE-750ML',0),
('coca-cola-soft-drink','1.25 L',70,65,20,'COKE-1250ML',1),
('real-mixed-fruit-juice','1 L',120,110,25,'REALJUICE-1L',0),
('kellogg-s-corn-flakes','475 g',235,215,18,'CORNFLAKES-475G',0),
('aashirvaad-poha','500 g',45,40,40,'POHA-500G',0),
('saffola-oats','500 g',99,89,25,'OATS-500G',0),
('saffola-oats','1 kg',190,172,12,'OATS-1KG',1),
('johnson-s-baby-powder','100 g',95,88,25,'JBPOWDER-100G',0),
('johnson-s-baby-powder','400 g',290,269,10,'JBPOWDER-400G',1),
('pampers-baby-dry-pants','M - 9 pcs',199,182,20,'PAMPERS-M9',0),
('pampers-baby-dry-pants','L - 9 pcs',219,199,15,'PAMPERS-L9',1),
('lifebuoy-total-10-soap','125 g x1',38,34,60,'LIFEBUOY-1',0),
('lifebuoy-total-10-soap','Pack of 4',152,132,25,'LIFEBUOY-4',1),
('dettol-handwash-refill','750 ml',165,145,20,'DETTOLHW-750',0),
('parachute-coconut-hair-oil','175 ml',95,88,40,'PARACHUTE-175',0),
('parachute-coconut-hair-oil','500 ml',245,225,18,'PARACHUTE-500',1),
('clinic-plus-strong-long-shampoo','175 ml',99,90,30,'CLINIC-175',0),
('clinic-plus-strong-long-shampoo','340 ml',185,169,15,'CLINIC-340',1),
('nivea-soft-light-moisturiser','100 ml',199,179,15,'NIVEA-100',0),
('colgate-strong-teeth-toothpaste','100 g',60,55,50,'COLGATE-100G',0),
('colgate-strong-teeth-toothpaste','300 g',165,152,20,'COLGATE-300G',1),
('lizol-disinfectant-floor-cleaner','500 ml',115,102,25,'LIZOL-500',0),
('lizol-disinfectant-floor-cleaner','975 ml',210,189,12,'LIZOL-975',1),
('harpic-power-plus-toilet-cleaner','500 ml',99,89,25,'HARPIC-500',0),
('harpic-power-plus-toilet-cleaner','1 L',185,168,12,'HARPIC-1L',1),
('vim-dishwash-bar','140 g',10,10,80,'VIM-140G',0),
('vim-dishwash-bar','300 g',25,23,50,'VIM-300G',1),
('surf-excel-easy-wash-detergent-powder','500 g',70,63,40,'SURF-500G',0),
('surf-excel-easy-wash-detergent-powder','1 kg',135,122,25,'SURF-1KG',1),
('surf-excel-easy-wash-detergent-powder','4 kg',520,479,8,'SURF-4KG',2),
('rin-detergent-bar','250 g',20,18,60,'RIN-250G',0),
('comfort-fabric-conditioner','860 ml',210,189,12,'COMFORT-860',0),
('scotch-brite-scrub-pad','Pack of 3',65,58,30,'SCOTCH-3',0),
('homefoil-aluminium-foil','9 m',75,68,25,'FOIL-9M',0),
('cycle-pure-agarbatti-three-in-one','Small pack',35,32,50,'AGARBATTI-S',0),
('cycle-pure-agarbatti-three-in-one','Large pack',95,86,25,'AGARBATTI-L',1),
('mangaldeep-camphor-kapoor','50 g',70,63,30,'KAPOOR-50G',0),
('classmate-notebook-172-pages','1 pc',45,40,60,'NOTEBOOK-1',0),
('classmate-notebook-172-pages','Pack of 6',270,239,15,'NOTEBOOK-6',1),
('cello-butterflow-ball-pen','1 pc',10,10,100,'PEN-1',0),
('cello-butterflow-ball-pen','Pack of 5',50,45,40,'PEN-5',1),
('pedigree-adult-dog-food-chicken','1.2 kg',340,315,10,'PEDIGREE-1200',0)
) AS v(pslug,label,mrp,price,stock,sku,so) JOIN public.products p ON p.slug=v.pslug;

INSERT INTO public.coupons (code,description,discount_type,value,min_order,max_discount) VALUES
('WELCOME50','Flat Rs.50 off on orders above Rs.499','flat',50,499,NULL),
('SAVE10','10% off on orders above Rs.999 (max Rs.150)','percent',10,999,150),
('DIWALI15','Festival offer: 15% off above Rs.1499 (max Rs.300)','percent',15,1499,300);


-- PART 2: EXPANDED 230 GROCERY ITEMS & VARIANTS
-- Migration: Add Complete Grocery Catalog (Grains, Pulses, Spices, Oils, Dairy, Snacks, Beverages, Breakfast, Personal Care, Cleaning, Utensils, Misc)

-- 1. Insert new/missing categories
INSERT INTO public.categories (name, slug, icon, image_url, sort_order)
VALUES
  ('Cooking Utensils & Containers', 'utensils-cookware', '🍳', '/images/household.jpg', 25),
  ('Miscellaneous & Home Needs', 'misc-items', '📦', '/images/packaged.jpg', 26)
ON CONFLICT (slug) DO NOTHING;

-- 2. Insert Subcategories
INSERT INTO public.categories (parent_id, name, slug, sort_order)
SELECT c.id, v.name, v.slug, v.so
FROM (VALUES
  ('pulses-dal', 'Millets (Bajra / Jowar)', 'pulses-dal-millets', 10),
  ('pulses-dal', 'Whole Lentils', 'pulses-dal-whole-lentils', 11),
  ('spices-masala', 'Whole Exotic Spices', 'spices-masala-exotic', 18),
  ('oil-ghee', 'Specialty Cooking Oils', 'oil-ghee-specialty', 9),
  ('dairy', 'Paneer & Cheese', 'dairy-paneer-cheese', 8),
  ('dairy', 'Yogurt & Dahi', 'dairy-yogurt-dahi', 9),
  ('beverages', 'Traditional Drinks & Lassi', 'beverages-traditional', 7),
  ('utensils-cookware', 'Pots, Pans & Cookers', 'utensils-pots-pans', 0),
  ('utensils-cookware', 'Steel & Plastic Containers', 'utensils-containers', 1),
  ('utensils-cookware', 'Kitchen Tools & Cutlery', 'utensils-kitchen-tools', 2),
  ('misc-items', 'Electrical & Batteries', 'misc-electrical', 0),
  ('misc-items', 'Pooja & Household Misc', 'misc-household', 1)
) AS v(pslug, name, slug, so)
JOIN public.categories c ON c.slug = v.pslug
ON CONFLICT (slug) DO NOTHING;

-- 3. Insert Products
INSERT INTO public.products (name, slug, brand, category_id, subcategory_id, description, image_url, tags, is_featured, is_popular)
SELECT v.name, v.slug, v.brand, c.id, sc.id, v.descr, v.img, v.tags, v.feat, v.pop
FROM (VALUES
  -- Grains & Pulses
  ('Chana Dal (Bengal Gram)', 'chana-dal', 'Local Mill', 'pulses-dal', 'Chana Dal', 'Protein-rich yellow split Bengal gram.', '/images/products/moong-dal.svg', ARRAY['chana dal','pulses','dal'], false, true),
  ('Urad Dal Dhuli (White)', 'urad-dal-dhuli', 'Local Mill', 'pulses-dal', 'Urad Dal', 'Washed white urad dal for dal makhani, idli and dosa.', '/images/products/moong-dal.svg', ARRAY['urad dal','dal'], false, true),
  ('Pearl Millet (Desi Bajra)', 'pearl-millet-bajra', 'Local Farm', 'pulses-dal', 'Millets (Bajra / Jowar)', 'Nutritious whole grain pearl millet bajra.', '/images/products/aashirvaad-atta.jpg', ARRAY['bajra','millet','grain'], false, false),
  ('Sorghum (Desi Jowar)', 'sorghum-jowar', 'Local Farm', 'pulses-dal', 'Millets (Bajra / Jowar)', 'High fiber gluten-free whole jowar grains.', '/images/products/aashirvaad-atta.jpg', ARRAY['jowar','sorghum','grain'], false, false),
  ('Black Chickpeas (Kala Chana)', 'black-chickpeas-kala-chana', 'Local Farm', 'pulses-dal', 'Black Chana', 'Organic black chickpeas kala chana.', '/images/products/kabuli-chana.svg', ARRAY['kala chana','chana','pulses'], false, true),
  ('Whole Red Lentils (Sabut Masoor)', 'whole-red-lentils-sabut-masoor', 'Local Farm', 'pulses-dal', 'Whole Lentils', 'Unpolished whole brown-red masoor lentils.', '/images/products/masoor-dal.svg', ARRAY['sabut masoor','masoor','dal'], false, false),
  ('Green Gram Whole (Sabut Moong)', 'green-gram-sabut-moong', 'Local Farm', 'pulses-dal', 'Whole Lentils', 'Whole green moong beans for sprouts and cooking.', '/images/products/moong-dal.svg', ARRAY['sabut moong','green gram','dal'], false, true),
  ('Black Lentils (Urad Sabut Kali Dal)', 'black-lentils-urad-sabut', 'Local Farm', 'pulses-dal', 'Whole Lentils', 'Whole black gram for authentic Dal Makhani.', '/images/products/rajma-chitra.svg', ARRAY['kali dal','urad sabut','dal'], false, true),

  -- Spices
  ('Catch Hing (Asafoetida)', 'catch-hing-asafoetida', 'Catch', 'spices-masala', 'Hing', 'Strong aromatic compound asafoetida powder.', '/images/products/catch-jeera.svg', ARRAY['hing','asafoetida','spice'], false, true),
  ('Green Cardamom (Choti Elaichi)', 'green-cardamom-choti-elaichi', 'Royal Spices', 'spices-masala', 'Cardamom', 'Aromatic bold green cardamom pods.', '/images/products/catch-jeera.svg', ARRAY['elaichi','cardamom','spice'], false, true),
  ('Cinnamon Sticks (Dalchini)', 'cinnamon-sticks-dalchini', 'Royal Spices', 'spices-masala', 'Cinnamon', 'Pure rolled bark cinnamon dalchini.', '/images/products/catch-jeera.svg', ARRAY['dalchini','cinnamon','spice'], false, false),
  ('Whole Cloves (Laung)', 'whole-cloves-laung', 'Royal Spices', 'spices-masala', 'Cloves', 'Aromatic spicy whole cloves laung.', '/images/products/catch-jeera.svg', ARRAY['laung','cloves','spice'], false, false),
  ('Black Pepper (Kali Mirch Whole)', 'black-pepper-kali-mirch', 'Royal Spices', 'spices-masala', 'Black Pepper', 'Whole bold black peppercorns.', '/images/products/catch-jeera.svg', ARRAY['kali mirch','black pepper','spice'], false, true),
  ('Fennel Seeds (Moti Saunf)', 'fennel-seeds-saunf', 'Royal Spices', 'spices-masala', 'Fennel', 'Sweet aromatic green fennel seeds.', '/images/products/catch-jeera.svg', ARRAY['saunf','fennel','spice'], false, false),
  ('Fenugreek Seeds (Methi Dana)', 'fenugreek-seeds-methi', 'Royal Spices', 'spices-masala', 'Methi', 'Clean bitter aromatic methi seeds.', '/images/products/catch-jeera.svg', ARRAY['methi','fenugreek','spice'], false, false),
  ('Dry Mango Powder (Amchur)', 'dry-mango-powder-amchur', 'Everest', 'spices-masala', 'Garam Masala', 'Tangy dried green mango powder.', '/images/products/everest-turmeric.jpg', ARRAY['amchur','mango powder','spice'], false, false),
  ('Bay Leaves (Tej Patta)', 'bay-leaves-tej-patta', 'Royal Spices', 'spices-masala', 'Bay Leaf', 'Aromatic dried bay leaves for biryani & curries.', '/images/products/everest-dhaniya.svg', ARRAY['tej patta','bay leaf','spice'], false, false),
  ('Pure Kashmiri Saffron (Kesar)', 'pure-kashmiri-saffron-kesar', 'Baby Brand', 'spices-masala', 'Whole Exotic Spices', '100% pure organic Mongra Kashmiri kesar.', '/images/products/everest-turmeric.jpg', ARRAY['kesar','saffron','spice'], true, false),
  ('Carom Seeds (Desi Ajwain)', 'carom-seeds-ajwain', 'Royal Spices', 'spices-masala', 'Ajwain', 'Digestive fragrant carom seeds ajwain.', '/images/products/catch-jeera.svg', ARRAY['ajwain','carom','spice'], false, true),
  ('Whole Nutmeg (Jaiphal)', 'whole-nutmeg-jaiphal', 'Royal Spices', 'spices-masala', 'Whole Exotic Spices', 'Whole aromatic nutmeg nuts jaiphal.', '/images/products/catch-jeera.svg', ARRAY['jaiphal','nutmeg','spice'], false, false),
  ('Star Anise (Chakra Phool)', 'star-anise-chakra-phool', 'Royal Spices', 'spices-masala', 'Whole Exotic Spices', 'Whole star anise for biryani & garam masala.', '/images/products/catch-jeera.svg', ARRAY['chakra phool','star anise','spice'], false, false),

  -- Cooking Oils
  ('Fortune Soyabean Oil', 'fortune-soyabean-oil', 'Fortune', 'oil-ghee', 'Soybean Oil', 'Light and healthy refined soybean cooking oil.', '/images/products/fortune-sunflower-oil.svg', ARRAY['soyabean oil','cooking oil'], false, true),
  ('Dhara Refined Peanut Oil', 'dhara-peanut-oil', 'Dhara', 'oil-ghee', 'Groundnut Oil', 'Filtered pure groundnut peanut cooking oil.', '/images/products/fortune-sunflower-oil.svg', ARRAY['peanut oil','groundnut oil'], false, false),
  ('Figaro Pure Olive Oil', 'figaro-pure-olive-oil', 'Figaro', 'oil-ghee', 'Olive Oil', 'Imported pure Spanish olive oil for cooking.', '/images/products/patanjali-mustard-oil.svg', ARRAY['olive oil','figaro'], false, false),
  ('Tilsona Pure Sesame Oil (Til Tel)', 'tilsona-sesame-oil', 'Tilsona', 'oil-ghee', 'Specialty Cooking Oils', 'Pure cold pressed sesame gingelly oil.', '/images/products/patanjali-mustard-oil.svg', ARRAY['sesame oil','til tel'], false, false),
  ('Fortune Rice Bran Health Oil', 'fortune-rice-bran-oil', 'Fortune', 'oil-ghee', 'Rice Bran Oil', 'Physically refined rice bran oil with Gamma Oryzanol.', '/images/products/fortune-sunflower-oil.svg', ARRAY['rice bran oil','cooking oil'], false, true),
  ('Dalda Vanaspati Ghee', 'dalda-vanaspati-ghee', 'Dalda', 'oil-ghee', 'Vanaspati', 'Traditional hydrogenated vegetable ghee for puris & sweets.', '/images/products/amul-desi-ghee.jpg', ARRAY['dalda','vanaspati'], false, false),

  -- Dairy Products
  ('Amul Masti Dahi (Curd)', 'amul-masti-dahi', 'Amul', 'dairy', 'Curd', 'Thick, creamy and delicious pasteurised curd.', '/images/products/amul-milk.svg', ARRAY['dahi','curd','dairy'], false, true),
  ('Amul Fresh Malai Paneer', 'amul-fresh-malai-paneer', 'Amul', 'dairy', 'Paneer', 'Soft, rich cottage cheese cubes.', '/images/products/amul-butter.svg', ARRAY['paneer','cottage cheese','dairy'], true, true),
  ('Amul Fresh Cream', 'amul-fresh-cream', 'Amul', 'dairy', 'Cream', 'Sterilised low fat dairy cooking cream.', '/images/products/amul-milk.svg', ARRAY['cream','malai','dairy'], false, false),
  ('Amul Spiced Buttermilk (Chhaachh)', 'amul-spiced-buttermilk', 'Amul', 'dairy', 'Lassi', 'Refreshing spiced buttermilk pouch.', '/images/products/amul-milk.svg', ARRAY['chhaachh','buttermilk','dairy'], false, true),
  ('Nestle Everyday Dairy Whitener Milk Powder', 'nestle-everyday-milk-powder', 'Nestle', 'dairy', 'Milk', 'Rich dairy whitener powder for thick tea.', '/images/products/amul-milk.svg', ARRAY['milk powder','dairy whitener'], false, true),
  ('Nestle Milkmaid Sweetened Condensed Milk', 'nestle-milkmaid-condensed-milk', 'Nestle', 'dairy', 'Milk', 'Sweetened condensed milk for kheer and desserts.', '/images/products/amul-desi-ghee.jpg', ARRAY['condensed milk','milkmaid'], false, true),
  ('Amul Cheese Slices', 'amul-cheese-slices', 'Amul', 'dairy', 'Cheese', 'Processed cheese slices for sandwiches and burgers.', '/images/products/amul-butter.svg', ARRAY['cheese','cheese slices'], false, true),

  -- Snacks & Sweets
  ('Haldiram Rasgulla Tin', 'haldiram-rasgulla-tin', 'Haldirams', 'chocolates', 'Chocolates', 'Spongy, syrupy traditional cottage cheese sweet.', '/images/products/amul-desi-ghee.jpg', ARRAY['rasgulla','sweets','mithai'], false, true),
  ('Haldiram Gulab Jamun Tin', 'haldiram-gulab-jamun-tin', 'Haldirams', 'chocolates', 'Chocolates', 'Soft melt-in-mouth gulab jamuns in sugar syrup.', '/images/products/amul-desi-ghee.jpg', ARRAY['gulab jamun','sweets','mithai'], false, true),
  ('MTR 3-Minute Breakfast Khatta Meetha Poha', 'mtr-breakfast-poha', 'MTR', 'packaged-foods', 'Poha', 'Instant ready to eat traditional spiced poha.', '/images/products/aashirvaad-poha.svg', ARRAY['poha','breakfast','mtr'], false, false),
  ('MTR Instant Rava Upma Mix', 'mtr-instant-rava-upma', 'MTR', 'packaged-foods', 'Ready Meals', 'Instant savoury semolina upma breakfast mix.', '/images/products/bansi-suji.svg', ARRAY['upma','rava upma','mtr'], false, false),

  -- Beverages
  ('Lipton Green Tea Honey Lemon', 'lipton-green-tea-honey-lemon', 'Lipton', 'tea-coffee', 'Green Tea', 'Pure antioxidant-rich green tea bags.', '/images/products/tata-tea-premium.svg', ARRAY['green tea','lipton'], false, true),
  ('Red Bull Energy Drink', 'red-bull-energy-drink', 'Red Bull', 'beverages', 'Energy Drinks', 'Vitalizes body and mind energy drink can.', '/images/products/coca-cola.svg', ARRAY['red bull','energy drink'], false, false),
  ('Amul Kool Cafe Flavoured Milk', 'amul-kool-cafe', 'Amul', 'beverages', 'Flavoured Milk', 'Chilled coffee flavoured milk can.', '/images/products/coca-cola.svg', ARRAY['amul kool','flavoured milk'], false, false),
  ('Real Coconut Water (100% Tender)', 'real-tender-coconut-water', 'Real', 'beverages', 'Juice', 'Natural refreshing tender coconut water.', '/images/products/real-fruit-juice.svg', ARRAY['coconut water','nariyal pani'], false, true),

  -- Breakfast
  ('Britannia 100% Whole Wheat Bread', 'britannia-whole-wheat-bread', 'Britannia', 'breakfast', 'Bread', 'Freshly baked whole wheat brown sandwich bread.', '/images/products/parle-g.jpg', ARRAY['bread','wheat bread'], false, true),
  ('Fresh Farm White Eggs (Pack of 6)', 'fresh-farm-white-eggs-6pcs', 'Poultry Fresh', 'breakfast', 'Bread', 'Freshly farm-harvested protein eggs.', '/images/products/parle-g.jpg', ARRAY['eggs','farm eggs'], false, true),
  ('Kissan Mixed Fruit Jam', 'kissan-mixed-fruit-jam', 'Kissan', 'sauces-spreads', 'Jam', 'Sweet tangy spread made with 8 real fruits.', '/images/products/mothers-pickle.svg', ARRAY['jam','fruit jam'], false, true),
  ('Pintola All Natural Peanut Butter', 'pintola-peanut-butter-crunchy', 'Pintola', 'sauces-spreads', 'Peanut Butter', 'High protein crunchy roasted peanut spread.', '/images/products/mothers-pickle.svg', ARRAY['peanut butter','pintola'], false, true),
  ('Kellogg Muesli Fruit Nut & Seeds', 'kellogg-muesli-fruit-nut', 'Kelloggs', 'packaged-foods', 'Breakfast Cereals', 'Crunchy grains with cranberries, raisins & almonds.', '/images/products/kelloggs-cornflakes.svg', ARRAY['muesli','cereal'], false, false),
  ('Nutella Hazelnut Cocoa Spread', 'nutella-hazelnut-spread', 'Ferrero', 'sauces-spreads', 'Jam', 'Creamy hazelnut and chocolate breakfast spread.', '/images/products/cadbury-dairy-milk.jpg', ARRAY['nutella','hazelnut spread'], false, true),

  -- Personal Care
  ('Dettol Original Bathing Soap', 'dettol-original-soap', 'Dettol', 'personal-care', 'Soap', 'Trusted antiseptic germ protection bathing bar.', '/images/products/lifebuoy-soap.svg', ARRAY['dettol soap','soap'], false, true),
  ('Head & Shoulders Cool Menthol Shampoo', 'head-shoulders-cool-menthol', 'Head & Shoulders', 'hair-care', 'Shampoo', 'Anti-dandruff cool menthol refreshing shampoo.', '/images/products/clinic-plus-shampoo.svg', ARRAY['shampoo','head shoulders'], false, true),
  ('Oral-B Shiny Clean Toothbrush (Medium)', 'oral-b-toothbrush-shiny-clean', 'Oral-B', 'oral-care', 'Toothbrush', 'Cross action plaque remover bristles.', '/images/products/colgate-toothpaste.svg', ARRAY['toothbrush','oral b'], false, true),
  ('Gillette Foamy Lemon Lime Shaving Foam', 'gillette-foamy-shaving-foam', 'Gillette', 'personal-care', 'Talcum Powder', 'Thick extra rich creamy lather for smooth shave.', '/images/products/johnsons-powder.svg', ARRAY['shaving foam','gillette'], false, false),
  ('Nivea Body Lotion Nourishing Deep Moisture', 'nivea-body-lotion-deep-moisture', 'Nivea', 'personal-care', 'Body Lotion', '48h intensive moisture care body lotion.', '/images/products/nivea-soft.svg', ARRAY['body lotion','nivea'], false, true),
  ('Fogg Scent Master Deodorant for Men', 'fogg-scent-deodorant', 'Fogg', 'personal-care', 'Deodorant', 'No gas long lasting body spray perfume.', '/images/products/johnsons-powder.svg', ARRAY['deodorant','fogg'], false, true),
  ('Garnier Men Acno Fight Face Wash', 'garnier-men-acno-fight-facewash', 'Garnier', 'personal-care', 'Face Wash', 'Anti-pimple charcoal clarifying face wash.', '/images/products/colgate-toothpaste.svg', ARRAY['facewash','garnier'], false, true),

  -- Cleaning & Household
  ('Colin Glass and Household Cleaner Spray', 'colin-glass-cleaner-spray', 'Colin', 'household-cleaning', 'Glass Cleaner', 'Shine booster streak-free glass cleaner spray.', '/images/products/lizol-cleaner.svg', ARRAY['colin','glass cleaner'], false, true),
  ('Pril Kraft Dishwash Gel Liquid', 'pril-dishwash-gel-liquid', 'Pril', 'household-cleaning', 'Dishwash', 'Active power drops grease remover liquid.', '/images/products/vim-bar.svg', ARRAY['dishwash liquid','pril'], false, true),
  ('Trishul White Phenyl Floor Disinfectant', 'trishul-white-phenyl', 'Trishul', 'household-cleaning', 'Phenyl', 'Pine scented white floor cleaning disinfectant.', '/images/products/lizol-cleaner.svg', ARRAY['phenyl','floor cleaner'], false, true),
  ('Odonil Room Air Freshener Lavender Block', 'odonil-air-freshener-lavender', 'Odonil', 'household-cleaning', 'Disinfectant', 'Long lasting natural fragrance block for rooms.', '/images/products/lifebuoy-soap.svg', ARRAY['air freshener','odonil'], false, true),
  ('Shalimar Premium Oxo-Biodegradable Garbage Bags', 'shalimar-garbage-bags-medium', 'Shalimar', 'kitchen-essentials', 'Garbage Bags', 'Tear resistant medium dustbin trash bags 30 pcs.', '/images/products/homefoil-foil.svg', ARRAY['garbage bags','trash bags'], false, true),
  ('Gala King Kong Grass Broom (Jhaadu)', 'gala-king-kong-grass-broom', 'Gala', 'household-cleaning', 'Floor Cleaner', 'Heavy duty fine Meghalaya grass dust broom.', '/images/products/homefoil-foil.svg', ARRAY['jhaadu','broom','gala'], false, true),
  ('Scotch-Brite Cotton Floor Mop (Pocha)', 'scotch-brite-cotton-floor-mop', 'Scotch-Brite', 'household-cleaning', 'Floor Cleaner', 'Loop end absorbent wet cotton floor cleaning mop.', '/images/products/scotch-brite.svg', ARRAY['mop','pocha'], false, true),
  ('Plastic Heavy Duty Water Bucket (Balti 18L)', 'plastic-water-bucket-18l', 'Milton', 'household-cleaning', 'Floor Cleaner', 'Sturdy plastic bathroom and utility washing bucket.', '/images/products/homefoil-foil.svg', ARRAY['bucket','balti'], false, false),

  -- Cookware & Utensils
  ('Hawkins Classic Aluminium Pressure Cooker (3L)', 'hawkins-pressure-cooker-3l', 'Hawkins', 'utensils-cookware', 'Pots, Pans & Cookers', 'Inner lid energy efficient pressure cooker.', '/images/products/homefoil-foil.svg', ARRAY['cooker','pressure cooker','hawkins'], true, true),
  ('Prestige Induction Base Non-Stick Dosa Tawa', 'prestige-nonstick-dosa-tawa', 'Prestige', 'utensils-cookware', 'Pots, Pans & Cookers', 'Durable scratch resistant flat pan for rotis & dosas.', '/images/products/homefoil-foil.svg', ARRAY['tawa','dosa tawa','prestige'], false, true),
  ('Prestige Heavy Hard Anodised Kadhai with Lid (2.5L)', 'prestige-anodised-kadhai', 'Prestige', 'utensils-cookware', 'Pots, Pans & Cookers', 'Deep frying wok kadhai for curries and vegetables.', '/images/products/homefoil-foil.svg', ARRAY['kadhai','wok','prestige'], false, true),
  ('Bajaj Classic 500W Mixer Grinder with 3 Jars', 'bajaj-mixer-grinder-500w', 'Bajaj', 'utensils-cookware', 'Kitchen Tools & Cutlery', 'Heavy duty motor for dry and wet spice grinding.', '/images/products/homefoil-foil.svg', ARRAY['mixer grinder','bajaj'], true, false),
  ('Wooden Chakla Belan Set for Rotis', 'wooden-chakla-belan-set', 'Kitchen Craft', 'utensils-cookware', 'Kitchen Tools & Cutlery', 'Heavy pure Sheesham wood rolling pin & board.', '/images/products/homefoil-foil.svg', ARRAY['chakla belan','rolling pin'], false, true),
  ('Stainless Steel Kitchen Knife & Peeler Set', 'steel-knife-peeler-set', 'Kitchen Craft', 'utensils-cookware', 'Kitchen Tools & Cutlery', 'Sharp stainless steel vegetable cutting knife & peeler.', '/images/products/homefoil-foil.svg', ARRAY['knife','peeler'], false, true),
  ('Stainless Steel Airtight Kitchen Storage Jars (Pack of 4)', 'steel-storage-jars-4pcs', 'Kitchen Craft', 'utensils-cookware', 'Steel & Plastic Containers', 'Rust-proof see-through window grocery storage containers.', '/images/products/homefoil-foil.svg', ARRAY['storage jars','dabba'], false, true),
  ('Stainless Steel Mesh Tea & Flour Colander (Chhalni)', 'steel-colander-chhalni', 'Kitchen Craft', 'utensils-cookware', 'Kitchen Tools & Cutlery', 'Fine wire mesh strainer for atta and tea.', '/images/products/homefoil-foil.svg', ARRAY['chhalni','strainer'], false, false),

  -- Miscellaneous & Home Needs
  ('Duracell Ultra AA Alkaline Batteries (Pack of 4)', 'duracell-aa-batteries-4pcs', 'Duracell', 'misc-items', 'Electrical & Batteries', 'Long lasting 100% power alkaline AA battery cells.', '/images/products/classmate-notebook.svg', ARRAY['batteries','duracell','aa'], false, true),
  ('Wipro Garnet 9W LED Bulb (Cool Day White)', 'wipro-9w-led-bulb', 'Wipro', 'misc-items', 'Electrical & Batteries', 'Energy saving high lumen B22 base LED bulb.', '/images/products/classmate-notebook.svg', ARRAY['led bulb','wipro','bulb'], false, true),
  ('Wax Safety Household Candles (Pack of 12)', 'household-white-candles-12pcs', 'Bright Home', 'misc-items', 'Pooja & Household Misc', 'Smokeless white emergency lighting candles.', '/images/products/mangaldeep-kapoor.svg', ARRAY['candles','mombatti'], false, true),
  ('Ship Safety Matchboxes (Bundle of 10 Boxes)', 'ship-safety-matchboxes-10pk', 'Ship', 'kitchen-essentials', 'Matchbox', 'Carbonized safety matchsticks for kitchen and pooja.', '/images/products/mangaldeep-kapoor.svg', ARRAY['matchbox','maachis'], false, true),
  ('Fevicol MR Squeezy Bottle Adhesive Glue (100g)', 'fevicol-mr-glue-100g', 'Fevicol', 'stationery', 'Glue', 'Non-staining synthetic craft and paper glue.', '/images/products/cello-pen.svg', ARRAY['fevicol','glue'], false, true),
  ('Multi-Purpose Kitchen & Craft Scissors', 'craft-kitchen-scissors', 'Kitchen Craft', 'misc-items', 'Pooja & Household Misc', 'Heavy duty sharp stainless steel grip scissors.', '/images/products/cello-pen.svg', ARRAY['scissors','kainchi'], false, false),
  ('Home Emergency Tailoring & Sewing Needle Kit', 'emergency-sewing-needle-kit', 'Stitch Craft', 'misc-items', 'Pooja & Household Misc', 'Assorted thread spools, needles, buttons and safety pins.', '/images/products/classmate-notebook.svg', ARRAY['sewing kit','needle'], false, false),
  ('Chef Gas Stove Spark Lighter for Kitchen', 'chef-gas-stove-lighter', 'Kitchen Craft', 'kitchen-essentials', 'Lighters', 'Durable stainless steel electronic kitchen gas lighter.', '/images/products/homefoil-foil.svg', ARRAY['gas lighter','lighter'], false, true)
) AS v(name, slug, brand, pslug, scname, descr, img, tags, feat, pop)
JOIN public.categories c ON c.slug = v.pslug
LEFT JOIN public.categories sc ON sc.slug = (c.slug || '-' || lower(regexp_replace(v.scname, '[^a-zA-Z0-9]+', '-', 'g')))
ON CONFLICT (slug) DO NOTHING;

-- 4. Insert Variants for New Products
INSERT INTO public.product_variants (product_id, label, mrp, price, stock, sku, sort_order)
SELECT p.id, v.label, v.mrp, v.price, v.stock, v.sku, v.so
FROM (VALUES
  -- Pulses & Grains
  ('chana-dal', '500 g', 50, 44, 40, 'CHANADAL-500G', 0),
  ('chana-dal', '1 kg', 95, 84, 50, 'CHANADAL-1KG', 1),
  ('urad-dal-dhuli', '500 g', 68, 59, 30, 'URADDAL-500G', 0),
  ('urad-dal-dhuli', '1 kg', 130, 116, 40, 'URADDAL-1KG', 1),
  ('pearl-millet-bajra', '1 kg', 45, 38, 50, 'BAJRA-1KG', 0),
  ('pearl-millet-bajra', '5 kg', 210, 180, 20, 'BAJRA-5KG', 1),
  ('sorghum-jowar', '1 kg', 60, 52, 40, 'JOWAR-1KG', 0),
  ('black-chickpeas-kala-chana', '500 g', 48, 42, 40, 'KALACHANA-500G', 0),
  ('black-chickpeas-kala-chana', '1 kg', 90, 79, 50, 'KALACHANA-1KG', 1),
  ('whole-red-lentils-sabut-masoor', '1 kg', 98, 86, 35, 'SABUTMASOOR-1KG', 0),
  ('green-gram-sabut-moong', '500 g', 65, 56, 35, 'SABUTMOONG-500G', 0),
  ('green-gram-sabut-moong', '1 kg', 125, 109, 40, 'SABUTMOONG-1KG', 1),
  ('black-lentils-urad-sabut', '1 kg', 135, 119, 30, 'URADSABUT-1KG', 0),

  -- Spices
  ('catch-hing-asafoetida', '50 g', 85, 78, 40, 'HING-50G', 0),
  ('green-cardamom-choti-elaichi', '50 g', 180, 160, 30, 'ELAICHI-50G', 0),
  ('green-cardamom-choti-elaichi', '100 g', 340, 299, 20, 'ELAICHI-100G', 1),
  ('cinnamon-sticks-dalchini', '100 g', 75, 65, 30, 'DALCHINI-100G', 0),
  ('whole-cloves-laung', '50 g', 60, 52, 35, 'LAUNG-50G', 0),
  ('whole-cloves-laung', '100 g', 115, 99, 25, 'LAUNG-100G', 1),
  ('black-pepper-kali-mirch', '100 g', 110, 95, 30, 'KALIMIRCH-100G', 0),
  ('fennel-seeds-saunf', '100 g', 55, 48, 40, 'SAUNF-100G', 0),
  ('fenugreek-seeds-methi', '100 g', 30, 25, 50, 'METHI-100G', 0),
  ('dry-mango-powder-amchur', '100 g', 60, 52, 40, 'AMCHUR-100G', 0),
  ('bay-leaves-tej-patta', '50 g', 35, 28, 50, 'TEJPATTA-50G', 0),
  ('pure-kashmiri-saffron-kesar', '1 g box', 240, 210, 20, 'KESAR-1G', 0),
  ('carom-seeds-ajwain', '100 g', 45, 38, 50, 'AJWAIN-100G', 0),
  ('whole-nutmeg-jaiphal', '50 g', 75, 65, 25, 'JAIPHAL-50G', 0),
  ('star-anise-chakra-phool', '50 g', 60, 52, 25, 'STARISE-50G', 0),

  -- Oils
  ('fortune-soyabean-oil', '1 L Pouch', 135, 118, 50, 'SOYAOIL-1L', 0),
  ('dhara-peanut-oil', '1 L Bottle', 185, 168, 30, 'PEANUT-1L', 0),
  ('figaro-pure-olive-oil', '500 ml', 390, 349, 15, 'FIGARO-500ML', 0),
  ('figaro-pure-olive-oil', '1 L Tin', 750, 680, 10, 'FIGARO-1L', 1),
  ('tilsona-sesame-oil', '500 ml', 140, 125, 25, 'TIL-500ML', 0),
  ('fortune-rice-bran-oil', '1 L Pouch', 140, 124, 40, 'RICEBRAN-1L', 0),
  ('dalda-vanaspati-ghee', '1 L Pouch', 115, 99, 40, 'DALDA-1L', 0),

  -- Dairy
  ('amul-masti-dahi', '200 g Cup', 25, 24, 50, 'AMULDAHI-200G', 0),
  ('amul-masti-dahi', '400 g Pouch', 35, 33, 40, 'AMULDAHI-400G', 1),
  ('amul-fresh-malai-paneer', '200 g Pack', 90, 85, 40, 'AMULPANEER-200G', 0),
  ('amul-fresh-cream', '250 ml', 70, 66, 30, 'AMULCREAM-250ML', 0),
  ('amul-spiced-buttermilk', '200 ml', 15, 14, 60, 'AMULCHHAACH-200', 0),
  ('nestle-everyday-milk-powder', '200 g', 110, 99, 30, 'NESTLEMP-200G', 0),
  ('nestle-everyday-milk-powder', '400 g', 210, 189, 20, 'NESTLEMP-400G', 1),
  ('nestle-milkmaid-condensed-milk', '380 g Tin', 145, 134, 30, 'MILKMAID-380G', 0),
  ('amul-cheese-slices', '10 Slices (200g)', 145, 135, 30, 'AMULCHEESE-200G', 0),

  -- Sweets & Breakfast
  ('haldiram-rasgulla-tin', '1 kg Tin', 240, 215, 25, 'RASGULLA-1KG', 0),
  ('haldiram-gulab-jamun-tin', '1 kg Tin', 250, 225, 25, 'GULABJAMUN-1KG', 0),
  ('mtr-breakfast-poha', '60 g Cup', 45, 40, 40, 'MTRPOHA-60G', 0),
  ('mtr-instant-rava-upma', '500 g Pack', 95, 84, 30, 'MTRUPMA-500G', 0),
  ('lipton-green-tea-honey-lemon', '25 Tea Bags', 190, 168, 30, 'LIPTONGT-25', 0),
  ('red-bull-energy-drink', '250 ml Can', 125, 115, 40, 'REDBULL-250ML', 0),
  ('amul-kool-cafe', '200 ml Can', 35, 32, 40, 'AMULCAFE-200ML', 0),
  ('real-tender-coconut-water', '200 ml Tetra', 50, 45, 50, 'COCO-200ML', 0),
  ('britannia-whole-wheat-bread', '400 g Loaf', 45, 40, 30, 'BRITBREAD-400G', 0),
  ('fresh-farm-white-eggs-6pcs', 'Pack of 6', 42, 38, 50, 'EGGS-6PCS', 0),
  ('kissan-mixed-fruit-jam', '500 g Jar', 170, 149, 30, 'KISSANJAM-500G', 0),
  ('pintola-peanut-butter-crunchy', '350 g', 175, 155, 25, 'PINTOLA-350G', 0),
  ('kellogg-muesli-fruit-nut', '500 g Pack', 340, 299, 15, 'MUESLI-500G', 0),
  ('nutella-hazelnut-spread', '350 g Jar', 390, 349, 20, 'NUTELLA-350G', 0),

  -- Personal Care
  ('dettol-original-soap', 'Pack of 4 (125g each)', 175, 152, 40, 'DETTOLSOAP-4', 0),
  ('head-shoulders-cool-menthol', '180 ml', 190, 169, 30, 'HNS-180ML', 0),
  ('oral-b-toothbrush-shiny-clean', 'Buy 2 Get 1 Free', 60, 50, 50, 'ORALB-3PK', 0),
  ('gillette-foamy-shaving-foam', '196 g Can', 160, 142, 25, 'GILLETTE-FOAM', 0),
  ('nivea-body-lotion-deep-moisture', '200 ml', 225, 195, 25, 'NIVEALOTION-200', 0),
  ('fogg-scent-deodorant', '120 ml', 250, 199, 30, 'FOGG-120ML', 0),
  ('garnier-men-acno-fight-facewash', '100 g', 199, 175, 30, 'GARNIER-100G', 0),

  -- Cleaning & Household
  ('colin-glass-cleaner-spray', '500 ml Spray', 110, 98, 40, 'COLIN-500ML', 0),
  ('pril-dishwash-gel-liquid', '425 ml Bottle', 115, 99, 40, 'PRIL-425ML', 0),
  ('trishul-white-phenyl', '1 L Bottle', 80, 68, 50, 'PHENYL-1L', 0),
  ('odonil-air-freshener-lavender', '50 g Block', 55, 48, 50, 'ODONIL-50G', 0),
  ('shalimar-garbage-bags-medium', 'Pack of 30 Bags', 95, 79, 40, 'GARBAGE-30', 0),
  ('gala-king-kong-grass-broom', '1 Pc', 150, 129, 30, 'GALA-BROOM', 0),
  ('scotch-brite-cotton-floor-mop', '1 Pc with Handle', 280, 245, 20, 'SCOTCH-MOP', 0),
  ('plastic-water-bucket-18l', '18 Litre Heavy', 180, 149, 25, 'BUCKET-18L', 0),

  -- Cookware & Utensils
  ('hawkins-pressure-cooker-3l', '3 Litre Inner Lid', 1450, 1299, 10, 'HAWKINS-3L', 0),
  ('prestige-nonstick-dosa-tawa', '28 cm Flat', 750, 599, 15, 'PRESTIGE-TAWA', 0),
  ('prestige-anodised-kadhai', '2.5 L with Glass Lid', 990, 799, 12, 'PRESTIGE-KADHAI', 0),
  ('bajaj-mixer-grinder-500w', '500W with 3 SS Jars', 2800, 2299, 8, 'BAJAJ-MIXER', 0),
  ('wooden-chakla-belan-set', 'Pure Sheesham Wood', 350, 279, 20, 'CHAKLA-BELAN', 0),
  ('steel-knife-peeler-set', 'Knife + Peeler Set', 120, 89, 40, 'KNIFE-SET', 0),
  ('steel-storage-jars-4pcs', 'Set of 4 Containers', 550, 429, 15, 'STEEL-JARS-4', 0),
  ('steel-colander-chhalni', 'Stainless Steel Mesh', 90, 69, 40, 'CHHALNI-MESH', 0),

  -- Misc
  ('duracell-aa-batteries-4pcs', 'Pack of 4', 160, 140, 40, 'DURACELL-AA4', 0),
  ('wipro-9w-led-bulb', '9W Cool White (B22)', 140, 99, 60, 'WIPRO-9W', 0),
  ('household-white-candles-12pcs', 'Pack of 12', 60, 48, 50, 'CANDLE-12', 0),
  ('ship-safety-matchboxes-10pk', 'Bundle of 10 Boxes', 20, 18, 100, 'MATCH-10PK', 0),
  ('fevicol-mr-glue-100g', '100 g Squeezy', 35, 30, 60, 'FEVICOL-100G', 0),
  ('craft-kitchen-scissors', '8-inch Stainless Steel', 120, 89, 30, 'SCISSORS-8IN', 0),
  ('emergency-sewing-needle-kit', 'Compact Travel Kit', 80, 59, 40, 'SEWING-KIT', 0),
  ('chef-gas-stove-lighter', 'Electronic Steel Lighter', 75, 55, 50, 'GAS-LIGHTER', 0)
) AS v(pslug, label, mrp, price, stock, sku, so)
JOIN public.products p ON p.slug = v.pslug
ON CONFLICT DO NOTHING;

