
REVOKE EXECUTE ON FUNCTION public.set_updated_at() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.log_order_event() FROM anon, authenticated;

INSERT INTO public.categories (name,slug,icon,image_url,sort_order) VALUES
('Atta & Flour','atta-flour','🌾','/images/atta.jpg',0),
('Rice','rice','🍚','/images/rice.jpg',1),
('Pulses & Dal','pulses-dal','🫘','/images/dal.jpg',2),
('Oil & Ghee','oil-ghee','🛢️','/images/oil.jpg',3),
('Spices & Masala','spices-masala','🌶️','/images/spices.jpg',4),
('Salt & Sugar','salt-sugar','🧂','/images/spices.jpg',5),
('Dry Fruits','dry-fruits','🥜','/images/dryfruits.jpg',6),
('Tea & Coffee','tea-coffee','☕','/images/tea.jpg',7),
('Biscuits','biscuits','🍪','/images/biscuits.jpg',8),
('Namkeen & Snacks','namkeen-snacks','🥨','/images/snacks.jpg',9),
('Chocolates','chocolates','🍫','/images/snacks.jpg',10),
('Noodles & Pasta','noodles-pasta','🍜','/images/packaged.jpg',11),
('Sauces & Spreads','sauces-spreads','🥫','/images/packaged.jpg',12),
('Dairy Products','dairy','🥛','/images/dairy.jpg',13),
('Beverages','beverages','🥤','/images/beverages.jpg',14),
('Packaged Foods','packaged-foods','📦','/images/packaged.jpg',15),
('Breakfast Items','breakfast','🥣','/images/packaged.jpg',16),
('Baby Products','baby-products','🍼','/images/baby.jpg',17),
('Personal Care','personal-care','🧴','/images/personal.jpg',18),
('Hair Care','hair-care','💇','/images/personal.jpg',19),
('Skin Care','skin-care','🧖','/images/personal.jpg',20),
('Oral Care','oral-care','🪥','/images/personal.jpg',21),
('Household Cleaning','household-cleaning','🧽','/images/household.jpg',22),
('Laundry','laundry','🧺','/images/household.jpg',23),
('Kitchen Essentials','kitchen-essentials','🍳','/images/household.jpg',24),
('Pooja Items','pooja-items','🪔','/images/pooja.jpg',25),
('Stationery','stationery','✏️','/images/stationery.jpg',26),
('Pet Supplies','pet-supplies','🐕','/images/packaged.jpg',27),
('Other','other','🛒','/images/packaged.jpg',28);

INSERT INTO public.categories (parent_id,name,slug,sort_order)
SELECT c.id,v.name,v.slug,v.so FROM (VALUES
('atta-flour','Wheat Atta','atta-flour-wheat-atta',0),
('atta-flour','Multigrain Atta','atta-flour-multigrain-atta',1),
('atta-flour','Maida','atta-flour-maida',2),
('atta-flour','Besan','atta-flour-besan',3),
('atta-flour','Suji / Rava','atta-flour-suji-rava',4),
('atta-flour','Rice Flour','atta-flour-rice-flour',5),
('atta-flour','Corn Flour','atta-flour-corn-flour',6),
('atta-flour','Millet Flour','atta-flour-millet-flour',7),
('atta-flour','Sattu','atta-flour-sattu',8),
('rice','Basmati Rice','rice-basmati-rice',0),
('rice','Non-Basmati Rice','rice-non-basmati-rice',1),
('rice','Sella Rice','rice-sella-rice',2),
('rice','Broken Rice','rice-broken-rice',3),
('rice','Brown Rice','rice-brown-rice',4),
('rice','Local Rice','rice-local-rice',5),
('pulses-dal','Toor Dal','pulses-dal-toor-dal',0),
('pulses-dal','Moong Dal','pulses-dal-moong-dal',1),
('pulses-dal','Masoor Dal','pulses-dal-masoor-dal',2),
('pulses-dal','Chana Dal','pulses-dal-chana-dal',3),
('pulses-dal','Urad Dal','pulses-dal-urad-dal',4),
('pulses-dal','Rajma','pulses-dal-rajma',5),
('pulses-dal','Kabuli Chana','pulses-dal-kabuli-chana',6),
('pulses-dal','Black Chana','pulses-dal-black-chana',7),
('pulses-dal','Lobia','pulses-dal-lobia',8),
('pulses-dal','Matar','pulses-dal-matar',9),
('oil-ghee','Mustard Oil','oil-ghee-mustard-oil',0),
('oil-ghee','Sunflower Oil','oil-ghee-sunflower-oil',1),
('oil-ghee','Soybean Oil','oil-ghee-soybean-oil',2),
('oil-ghee','Groundnut Oil','oil-ghee-groundnut-oil',3),
('oil-ghee','Rice Bran Oil','oil-ghee-rice-bran-oil',4),
('oil-ghee','Coconut Oil','oil-ghee-coconut-oil',5),
('oil-ghee','Olive Oil','oil-ghee-olive-oil',6),
('oil-ghee','Desi Ghee','oil-ghee-desi-ghee',7),
('oil-ghee','Vanaspati','oil-ghee-vanaspati',8),
('spices-masala','Turmeric','spices-masala-turmeric',0),
('spices-masala','Red Chilli','spices-masala-red-chilli',1),
('spices-masala','Coriander Powder','spices-masala-coriander-powder',2),
('spices-masala','Garam Masala','spices-masala-garam-masala',3),
('spices-masala','Chaat Masala','spices-masala-chaat-masala',4),
('spices-masala','Cumin','spices-masala-cumin',5),
('spices-masala','Black Pepper','spices-masala-black-pepper',6),
('spices-masala','Cardamom','spices-masala-cardamom',7),
('spices-masala','Cloves','spices-masala-cloves',8),
('spices-masala','Cinnamon','spices-masala-cinnamon',9),
('spices-masala','Bay Leaf','spices-masala-bay-leaf',10),
('spices-masala','Hing','spices-masala-hing',11),
('spices-masala','Mustard Seeds','spices-masala-mustard-seeds',12),
('spices-masala','Fennel','spices-masala-fennel',13),
('spices-masala','Ajwain','spices-masala-ajwain',14),
('spices-masala','Methi','spices-masala-methi',15),
('spices-masala','Whole Spices','spices-masala-whole-spices',16),
('spices-masala','Mixed Masala','spices-masala-mixed-masala',17),
('salt-sugar','Sugar','salt-sugar-sugar',0),
('salt-sugar','Brown Sugar','salt-sugar-brown-sugar',1),
('salt-sugar','Iodized Salt','salt-sugar-iodized-salt',2),
('salt-sugar','Rock Salt','salt-sugar-rock-salt',3),
('salt-sugar','Black Salt','salt-sugar-black-salt',4),
('salt-sugar','Jaggery','salt-sugar-jaggery',5),
('salt-sugar','Honey','salt-sugar-honey',6),
('dry-fruits','Almonds','dry-fruits-almonds',0),
('dry-fruits','Cashews','dry-fruits-cashews',1),
('dry-fruits','Raisins','dry-fruits-raisins',2),
('dry-fruits','Walnuts','dry-fruits-walnuts',3),
('dry-fruits','Pistachios','dry-fruits-pistachios',4),
('dry-fruits','Dates','dry-fruits-dates',5),
('dry-fruits','Mixed Dry Fruits','dry-fruits-mixed-dry-fruits',6),
('dry-fruits','Seeds','dry-fruits-seeds',7),
('tea-coffee','Tea','tea-coffee-tea',0),
('tea-coffee','Green Tea','tea-coffee-green-tea',1),
('tea-coffee','Black Tea','tea-coffee-black-tea',2),
('tea-coffee','Instant Coffee','tea-coffee-instant-coffee',3),
('tea-coffee','Coffee Powder','tea-coffee-coffee-powder',4),
('tea-coffee','Milk Powder','tea-coffee-milk-powder',5),
('biscuits','Glucose Biscuits','biscuits-glucose-biscuits',0),
('biscuits','Cream Biscuits','biscuits-cream-biscuits',1),
('biscuits','Marie','biscuits-marie',2),
('biscuits','Cookies','biscuits-cookies',3),
('biscuits','Crackers','biscuits-crackers',4),
('biscuits','Rusk','biscuits-rusk',5),
('namkeen-snacks','Bhujia','namkeen-snacks-bhujia',0),
('namkeen-snacks','Mixture','namkeen-snacks-mixture',1),
('namkeen-snacks','Chips','namkeen-snacks-chips',2),
('namkeen-snacks','Kurkure','namkeen-snacks-kurkure',3),
('namkeen-snacks','Popcorn','namkeen-snacks-popcorn',4),
('namkeen-snacks','Peanuts','namkeen-snacks-peanuts',5),
('namkeen-snacks','Roasted Chana','namkeen-snacks-roasted-chana',6),
('namkeen-snacks','Fryums','namkeen-snacks-fryums',7),
('chocolates','Chocolates','chocolates-chocolates',0),
('chocolates','Toffees','chocolates-toffees',1),
('chocolates','Candies','chocolates-candies',2),
('chocolates','Lollipops','chocolates-lollipops',3),
('chocolates','Wafers','chocolates-wafers',4),
('chocolates','Chewing Gum','chocolates-chewing-gum',5),
('noodles-pasta','Noodles','noodles-pasta-noodles',0),
('noodles-pasta','Pasta','noodles-pasta-pasta',1),
('noodles-pasta','Vermicelli','noodles-pasta-vermicelli',2),
('noodles-pasta','Instant Soup','noodles-pasta-instant-soup',3),
('noodles-pasta','Ready to Eat','noodles-pasta-ready-to-eat',4),
('sauces-spreads','Tomato Ketchup','sauces-spreads-tomato-ketchup',0),
('sauces-spreads','Chilli Sauce','sauces-spreads-chilli-sauce',1),
('sauces-spreads','Soy Sauce','sauces-spreads-soy-sauce',2),
('sauces-spreads','Mayonnaise','sauces-spreads-mayonnaise',3),
('sauces-spreads','Jam','sauces-spreads-jam',4),
('sauces-spreads','Peanut Butter','sauces-spreads-peanut-butter',5),
('sauces-spreads','Pickles','sauces-spreads-pickles',6),
('sauces-spreads','Chutneys','sauces-spreads-chutneys',7),
('dairy','Milk','dairy-milk',0),
('dairy','Curd','dairy-curd',1),
('dairy','Paneer','dairy-paneer',2),
('dairy','Butter','dairy-butter',3),
('dairy','Cheese','dairy-cheese',4),
('dairy','Cream','dairy-cream',5),
('dairy','Flavoured Milk','dairy-flavoured-milk',6),
('dairy','Lassi','dairy-lassi',7),
('beverages','Mineral Water','beverages-mineral-water',0),
('beverages','Soft Drinks','beverages-soft-drinks',1),
('beverages','Juice','beverages-juice',2),
('beverages','Energy Drinks','beverages-energy-drinks',3),
('beverages','Soda','beverages-soda',4),
('beverages','Sharbat','beverages-sharbat',5),
('beverages','Glucose Drinks','beverages-glucose-drinks',6),
('packaged-foods','Poha','packaged-foods-poha',0),
('packaged-foods','Oats','packaged-foods-oats',1),
('packaged-foods','Cornflakes','packaged-foods-cornflakes',2),
('packaged-foods','Breakfast Cereals','packaged-foods-breakfast-cereals',3),
('packaged-foods','Ready Meals','packaged-foods-ready-meals',4),
('breakfast','Bread','breakfast-bread',0),
('breakfast','Buns','breakfast-buns',1),
('breakfast','Cakes','breakfast-cakes',2),
('breakfast','Toast','breakfast-toast',3),
('breakfast','Cereals','breakfast-cereals',4),
('baby-products','Baby Soap','baby-products-baby-soap',0),
('baby-products','Baby Shampoo','baby-products-baby-shampoo',1),
('baby-products','Baby Powder','baby-products-baby-powder',2),
('baby-products','Baby Oil','baby-products-baby-oil',3),
('baby-products','Diapers','baby-products-diapers',4),
('baby-products','Baby Food','baby-products-baby-food',5),
('baby-products','Baby Wipes','baby-products-baby-wipes',6),
('personal-care','Soap','personal-care-soap',0),
('personal-care','Face Wash','personal-care-face-wash',1),
('personal-care','Body Lotion','personal-care-body-lotion',2),
('personal-care','Deodorant','personal-care-deodorant',3),
('personal-care','Perfume','personal-care-perfume',4),
('personal-care','Talcum Powder','personal-care-talcum-powder',5),
('personal-care','Hand Wash','personal-care-hand-wash',6),
('hair-care','Shampoo','hair-care-shampoo',0),
('hair-care','Hair Oil','hair-care-hair-oil',1),
('hair-care','Conditioner','hair-care-conditioner',2),
('hair-care','Hair Serum','hair-care-hair-serum',3),
('hair-care','Hair Colour','hair-care-hair-colour',4),
('skin-care','Moisturizer','skin-care-moisturizer',0),
('skin-care','Sunscreen','skin-care-sunscreen',1),
('skin-care','Cold Cream','skin-care-cold-cream',2),
('skin-care','Face Cream','skin-care-face-cream',3),
('oral-care','Toothpaste','oral-care-toothpaste',0),
('oral-care','Toothbrush','oral-care-toothbrush',1),
('oral-care','Mouthwash','oral-care-mouthwash',2),
('oral-care','Dental Floss','oral-care-dental-floss',3),
('household-cleaning','Floor Cleaner','household-cleaning-floor-cleaner',0),
('household-cleaning','Toilet Cleaner','household-cleaning-toilet-cleaner',1),
('household-cleaning','Dishwash','household-cleaning-dishwash',2),
('household-cleaning','Glass Cleaner','household-cleaning-glass-cleaner',3),
('household-cleaning','Disinfectant','household-cleaning-disinfectant',4),
('household-cleaning','Phenyl','household-cleaning-phenyl',5),
('household-cleaning','Bleach','household-cleaning-bleach',6),
('laundry','Detergent Powder','laundry-detergent-powder',0),
('laundry','Detergent Liquid','laundry-detergent-liquid',1),
('laundry','Detergent Bar','laundry-detergent-bar',2),
('laundry','Fabric Conditioner','laundry-fabric-conditioner',3),
('laundry','Stain Remover','laundry-stain-remover',4),
('kitchen-essentials','Aluminium Foil','kitchen-essentials-aluminium-foil',0),
('kitchen-essentials','Cling Film','kitchen-essentials-cling-film',1),
('kitchen-essentials','Garbage Bags','kitchen-essentials-garbage-bags',2),
('kitchen-essentials','Scrubbers','kitchen-essentials-scrubbers',3),
('kitchen-essentials','Sponges','kitchen-essentials-sponges',4),
('kitchen-essentials','Matchbox','kitchen-essentials-matchbox',5),
('kitchen-essentials','Lighters','kitchen-essentials-lighters',6),
('pooja-items','Agarbatti','pooja-items-agarbatti',0),
('pooja-items','Dhoop','pooja-items-dhoop',1),
('pooja-items','Camphor','pooja-items-camphor',2),
('pooja-items','Cotton Wicks','pooja-items-cotton-wicks',3),
('pooja-items','Diya','pooja-items-diya',4),
('pooja-items','Pooja Oil','pooja-items-pooja-oil',5),
('pooja-items','Kumkum','pooja-items-kumkum',6),
('pooja-items','Roli','pooja-items-roli',7),
('pooja-items','Pooja Samagri','pooja-items-pooja-samagri',8),
('stationery','Pens','stationery-pens',0),
('stationery','Pencils','stationery-pencils',1),
('stationery','Erasers','stationery-erasers',2),
('stationery','Notebooks','stationery-notebooks',3),
('stationery','Registers','stationery-registers',4),
('stationery','Glue','stationery-glue',5),
('stationery','Tape','stationery-tape',6),
('stationery','Markers','stationery-markers',7),
('pet-supplies','Pet Food','pet-supplies-pet-food',0),
('pet-supplies','Pet Treats','pet-supplies-pet-treats',1),
('pet-supplies','Pet Care','pet-supplies-pet-care',2)
) AS v(pslug,name,slug,so) JOIN public.categories c ON c.slug=v.pslug;

INSERT INTO public.products (name,slug,brand,category_id,subcategory_id,description,image_url,tags,is_featured,is_popular)
SELECT v.name,v.slug,v.brand,c.id,sc.id,v.descr,v.img,v.tags,v.feat,v.pop FROM (VALUES
('Fortune Chakki Fresh Atta','fortune-chakki-fresh-atta','Fortune','atta-flour','Wheat Atta','100% whole wheat chakki atta for soft, fluffy rotis.','/images/atta.jpg',ARRAY['atta','wheat','flour'],true,true),
('Aashirvaad Shudh Chakki Atta','aashirvaad-shudh-chakki-atta','Aashirvaad','atta-flour','Wheat Atta','Made from 100% MP wheat, sieved twice for perfect rotis.','/images/atta.jpg',ARRAY['atta','wheat'],true,true),
('Rajdhani Besan','rajdhani-besan','Rajdhani','atta-flour','Besan','Fine gram flour, ideal for pakoda, kadhi and sweets.','/images/atta.jpg',ARRAY['besan','gram flour'],false,true),
('Bansi Suji / Rava','bansi-suji-rava','Bansi','atta-flour','Suji / Rava','Coarse semolina for halwa, upma and idli.','/images/atta.jpg',ARRAY['suji','rava'],false,false),
('Shakti Bhog Maida','shakti-bhog-maida','Shakti Bhog','atta-flour','Maida','Refined flour for puri, naan and bakery use.','/images/atta.jpg',ARRAY['maida'],false,false),
('India Gate Classic Basmati Rice','india-gate-classic-basmati-rice','India Gate','rice','Basmati Rice','Long grain aged basmati with rich aroma.','/images/rice.jpg',ARRAY['rice','basmati'],true,true),
('Daawat Rozana Gold Basmati','daawat-rozana-gold-basmati','Daawat','rice','Basmati Rice','Everyday basmati rice, fluffy and non-sticky.','/images/rice.jpg',ARRAY['rice','basmati'],false,true),
('Sona Masoori Rice (Local)','sona-masoori-rice-local','Local','rice','Non-Basmati Rice','Light and easy to digest daily rice.','/images/rice.jpg',ARRAY['rice','sona masoori'],false,false),
('Tata Sampann Toor Dal','tata-sampann-toor-dal','Tata Sampann','pulses-dal','Toor Dal','Unpolished toor dal, rich in protein.','/images/dal.jpg',ARRAY['dal','toor','arhar'],true,true),
('Moong Dal Dhuli','moong-dal-dhuli','Local','pulses-dal','Moong Dal','Split washed moong dal, cooks fast.','/images/dal.jpg',ARRAY['dal','moong'],false,true),
('Masoor Dal','masoor-dal','Local','pulses-dal','Masoor Dal','Everyday red lentils.','/images/dal.jpg',ARRAY['dal','masoor'],false,false),
('Rajma Chitra','rajma-chitra','Local','pulses-dal','Rajma','Premium chitra rajma kidney beans.','/images/dal.jpg',ARRAY['rajma'],false,false),
('Kabuli Chana','kabuli-chana','Local','pulses-dal','Kabuli Chana','Big size white chana for chole.','/images/dal.jpg',ARRAY['chana','chole'],false,false),
('Fortune Kachi Ghani Mustard Oil','fortune-kachi-ghani-mustard-oil','Fortune','oil-ghee','Mustard Oil','Cold pressed kachi ghani mustard oil.','/images/oil.jpg',ARRAY['oil','mustard','sarso'],true,true),
('Patanjali Kachi Ghani Sarson Tel','patanjali-kachi-ghani-sarson-tel','Patanjali','oil-ghee','Mustard Oil','Pure mustard oil with strong aroma.','/images/oil.jpg',ARRAY['oil','mustard'],false,true),
('Fortune Sunlite Refined Sunflower Oil','fortune-sunlite-refined-sunflower-oil','Fortune','oil-ghee','Sunflower Oil','Light and healthy refined sunflower oil.','/images/oil.jpg',ARRAY['oil','sunflower'],false,true),
('Amul Pure Desi Ghee','amul-pure-desi-ghee','Amul','oil-ghee','Desi Ghee','Made from cow milk, rich aroma and taste.','/images/oil.jpg',ARRAY['ghee','amul'],true,true),
('Everest Turmeric Powder (Haldi)','everest-turmeric-powder-haldi','Everest','spices-masala','Turmeric','Bright colour, pure haldi powder.','/images/spices.jpg',ARRAY['haldi','turmeric','masala'],false,true),
('MDH Deggi Mirch','mdh-deggi-mirch','MDH','spices-masala','Red Chilli','Rich red colour with mild heat.','/images/spices.jpg',ARRAY['mirch','chilli'],false,false),
('Everest Garam Masala','everest-garam-masala','Everest','spices-masala','Garam Masala','Classic blend of whole spices.','/images/spices.jpg',ARRAY['garam masala'],false,true),
('Catch Jeera Whole','catch-jeera-whole','Catch','spices-masala','Cumin','Aromatic whole cumin seeds.','/images/spices.jpg',ARRAY['jeera','cumin'],false,false),
('Everest Dhaniya Powder','everest-dhaniya-powder','Everest','spices-masala','Coriander Powder','Fresh ground coriander powder.','/images/spices.jpg',ARRAY['dhaniya','coriander'],false,false),
('Tata Salt Iodised','tata-salt-iodised','Tata','salt-sugar','Iodized Salt','Desh ka namak - vacuum evaporated iodised salt.','/images/spices.jpg',ARRAY['salt','namak'],true,true),
('Madhur Pure Sugar','madhur-pure-sugar','Madhur','salt-sugar','Sugar','Sparkling white refined sugar.','/images/spices.jpg',ARRAY['sugar','cheeni'],false,true),
('Organic Gud (Jaggery) Block','organic-gud-jaggery-block','Local','salt-sugar','Jaggery','Chemical-free jaggery from local mill.','/images/spices.jpg',ARRAY['gud','jaggery'],false,false),
('Dabur Honey','dabur-honey','Dabur','salt-sugar','Honey','100% pure honey, no sugar added.','/images/spices.jpg',ARRAY['honey','shahad'],false,false),
('California Almonds (Badam)','california-almonds-badam','Premium','dry-fruits','Almonds','Crunchy premium California almonds.','/images/dryfruits.jpg',ARRAY['badam','almond','dry fruit'],true,true),
('Whole Cashew W320 (Kaju)','whole-cashew-w320-kaju','Premium','dry-fruits','Cashews','Grade W320 whole cashew nuts.','/images/dryfruits.jpg',ARRAY['kaju','cashew'],false,true),
('Kishmish (Raisins)','kishmish-raisins','Premium','dry-fruits','Raisins','Seedless golden raisins.','/images/dryfruits.jpg',ARRAY['kishmish','raisin'],false,false),
('Tata Tea Premium','tata-tea-premium','Tata Tea','tea-coffee','Tea','Strong, refreshing Assam blend.','/images/tea.jpg',ARRAY['chai','tea'],true,true),
('Red Label Natural Care Tea','red-label-natural-care-tea','Brooke Bond','tea-coffee','Tea','Tea with 5 ayurvedic ingredients.','/images/tea.jpg',ARRAY['chai','tea'],false,true),
('Nescafe Classic Instant Coffee','nescafe-classic-instant-coffee','Nescafe','tea-coffee','Instant Coffee','100% pure instant coffee.','/images/tea.jpg',ARRAY['coffee'],false,false),
('Parle-G Original Glucose Biscuits','parle-g-original-glucose-biscuits','Parle','biscuits','Glucose Biscuits','India''s favourite glucose biscuit.','/images/biscuits.jpg',ARRAY['biscuit','parle-g'],false,true),
('Britannia Good Day Cashew Cookies','britannia-good-day-cashew-cookies','Britannia','biscuits','Cookies','Buttery cookies loaded with cashew.','/images/biscuits.jpg',ARRAY['biscuit','cookies'],false,true),
('Sunfeast Marie Light','sunfeast-marie-light','Sunfeast','biscuits','Marie','Light tea-time marie biscuits.','/images/biscuits.jpg',ARRAY['biscuit','marie'],false,false),
('Haldiram''s Aloo Bhujia','haldiram-s-aloo-bhujia','Haldiram''s','namkeen-snacks','Bhujia','Crispy spicy potato bhujia.','/images/snacks.jpg',ARRAY['namkeen','bhujia'],true,true),
('Bikaji Bikaneri Bhujia','bikaji-bikaneri-bhujia','Bikaji','namkeen-snacks','Bhujia','Authentic Bikaneri bhujia.','/images/snacks.jpg',ARRAY['namkeen'],false,false),
('Lay''s India''s Magic Masala','lay-s-india-s-magic-masala','Lay''s','namkeen-snacks','Chips','Crunchy potato chips with masala.','/images/snacks.jpg',ARRAY['chips','snacks'],false,true),
('Cadbury Dairy Milk','cadbury-dairy-milk','Cadbury','chocolates','Chocolates','Smooth creamy milk chocolate.','/images/snacks.jpg',ARRAY['chocolate'],false,true),
('Maggi 2-Minute Masala Noodles','maggi-2-minute-masala-noodles','Maggi','noodles-pasta','Noodles','Everyone''s favourite instant noodles.','/images/packaged.jpg',ARRAY['maggi','noodles'],true,true),
('Sunfeast Yippee Pasta Masala','sunfeast-yippee-pasta-masala','Sunfeast','noodles-pasta','Pasta','Instant pasta with masala mix.','/images/packaged.jpg',ARRAY['pasta'],false,false),
('Kissan Fresh Tomato Ketchup','kissan-fresh-tomato-ketchup','Kissan','sauces-spreads','Tomato Ketchup','Made from 100% real tomatoes.','/images/packaged.jpg',ARRAY['ketchup','sauce'],false,true),
('Mother''s Recipe Mango Pickle','mother-s-recipe-mango-pickle','Mother''s Recipe','sauces-spreads','Pickles','Traditional mango achar.','/images/packaged.jpg',ARRAY['pickle','achar'],false,false),
('Amul Taaza Toned Milk','amul-taaza-toned-milk','Amul','dairy','Milk','Homogenised toned milk, tetra pack.','/images/dairy.jpg',ARRAY['milk','dudh'],false,true),
('Amul Butter','amul-butter','Amul','dairy','Butter','Utterly butterly delicious.','/images/dairy.jpg',ARRAY['butter'],false,true),
('Bisleri Mineral Water','bisleri-mineral-water','Bisleri','beverages','Mineral Water','Packaged drinking water.','/images/beverages.jpg',ARRAY['water'],false,false),
('Coca-Cola Soft Drink','coca-cola-soft-drink','Coca-Cola','beverages','Soft Drinks','Chilled refreshment.','/images/beverages.jpg',ARRAY['cold drink'],false,false),
('Real Mixed Fruit Juice','real-mixed-fruit-juice','Real','beverages','Juice','No preservatives fruit juice.','/images/beverages.jpg',ARRAY['juice'],false,false),
('Kellogg''s Corn Flakes','kellogg-s-corn-flakes','Kellogg''s','packaged-foods','Cornflakes','Crispy golden flakes of corn.','/images/packaged.jpg',ARRAY['cornflakes','breakfast'],false,false),
('Aashirvaad Poha','aashirvaad-poha','Aashirvaad','packaged-foods','Poha','Thick flattened rice for breakfast.','/images/packaged.jpg',ARRAY['poha'],false,false),
('Saffola Oats','saffola-oats','Saffola','packaged-foods','Oats','100% natural wholegrain oats.','/images/packaged.jpg',ARRAY['oats'],false,false),
('Johnson''s Baby Powder','johnson-s-baby-powder','Johnson''s','baby-products','Baby Powder','Gentle powder for baby''s soft skin.','/images/baby.jpg',ARRAY['baby'],false,false),
('Pampers Baby Dry Pants','pampers-baby-dry-pants','Pampers','baby-products','Diapers','Up to 12 hours dryness.','/images/baby.jpg',ARRAY['diaper','baby'],false,true),
('Lifebuoy Total 10 Soap','lifebuoy-total-10-soap','Lifebuoy','personal-care','Soap','Germ protection bathing soap.','/images/personal.jpg',ARRAY['soap'],false,true),
('Dettol Handwash Refill','dettol-handwash-refill','Dettol','personal-care','Hand Wash','Kills 99.9% germs.','/images/personal.jpg',ARRAY['handwash'],false,false),
('Parachute Coconut Hair Oil','parachute-coconut-hair-oil','Parachute','hair-care','Hair Oil','100% pure coconut oil.','/images/personal.jpg',ARRAY['hair oil','coconut'],false,true),
('Clinic Plus Strong & Long Shampoo','clinic-plus-strong-long-shampoo','Clinic Plus','hair-care','Shampoo','Milk protein shampoo for strong hair.','/images/personal.jpg',ARRAY['shampoo'],false,false),
('Nivea Soft Light Moisturiser','nivea-soft-light-moisturiser','Nivea','skin-care','Moisturizer','Light non-greasy moisturiser.','/images/personal.jpg',ARRAY['cream','skin'],false,false),
('Colgate Strong Teeth Toothpaste','colgate-strong-teeth-toothpaste','Colgate','oral-care','Toothpaste','Calcium boost for strong teeth.','/images/personal.jpg',ARRAY['toothpaste'],false,true),
('Lizol Disinfectant Floor Cleaner','lizol-disinfectant-floor-cleaner','Lizol','household-cleaning','Floor Cleaner','Kills 99.9% germs, citrus fragrance.','/images/household.jpg',ARRAY['floor cleaner'],false,true),
('Harpic Power Plus Toilet Cleaner','harpic-power-plus-toilet-cleaner','Harpic','household-cleaning','Toilet Cleaner','Thick liquid, 10x better cleaning.','/images/household.jpg',ARRAY['toilet cleaner'],false,false),
('Vim Dishwash Bar','vim-dishwash-bar','Vim','household-cleaning','Dishwash','Lemon power on tough grease.','/images/household.jpg',ARRAY['dishwash'],false,false),
('Surf Excel Easy Wash Detergent Powder','surf-excel-easy-wash-detergent-powder','Surf Excel','laundry','Detergent Powder','Removes tough stains easily.','/images/household.jpg',ARRAY['detergent','surf'],true,true),
('Rin Detergent Bar','rin-detergent-bar','Rin','laundry','Detergent Bar','Powerful whiteness bar.','/images/household.jpg',ARRAY['detergent'],false,false),
('Comfort Fabric Conditioner','comfort-fabric-conditioner','Comfort','laundry','Fabric Conditioner','Softness and long lasting fragrance.','/images/household.jpg',ARRAY['fabric'],false,false),
('Scotch-Brite Scrub Pad','scotch-brite-scrub-pad','Scotch-Brite','kitchen-essentials','Scrubbers','Tough on grease, easy on hands.','/images/household.jpg',ARRAY['scrub'],false,false),
('Homefoil Aluminium Foil','homefoil-aluminium-foil','Homefoil','kitchen-essentials','Aluminium Foil','Keeps food fresh and warm.','/images/household.jpg',ARRAY['foil'],false,false),
('Cycle Pure Agarbatti Three-in-One','cycle-pure-agarbatti-three-in-one','Cycle','pooja-items','Agarbatti','Classic fragrance incense sticks.','/images/pooja.jpg',ARRAY['agarbatti','pooja'],false,true),
('Mangaldeep Camphor (Kapoor)','mangaldeep-camphor-kapoor','Mangaldeep','pooja-items','Camphor','Pure camphor tablets for aarti.','/images/pooja.jpg',ARRAY['kapoor','pooja'],false,false),
('Classmate Notebook 172 Pages','classmate-notebook-172-pages','Classmate','stationery','Notebooks','Single line ruled notebook.','/images/stationery.jpg',ARRAY['notebook','copy'],false,false),
('Cello Butterflow Ball Pen','cello-butterflow-ball-pen','Cello','stationery','Pens','Smooth writing blue ball pen.','/images/stationery.jpg',ARRAY['pen'],false,false),
('Pedigree Adult Dog Food Chicken','pedigree-adult-dog-food-chicken','Pedigree','pet-supplies','Pet Food','Complete nutrition for adult dogs.','/images/packaged.jpg',ARRAY['dog food'],false,false)
) AS v(name,slug,brand,cslug,subname,descr,img,tags,feat,pop)
JOIN public.categories c ON c.slug=v.cslug
LEFT JOIN public.categories sc ON sc.parent_id=c.id AND sc.name=v.subname;

INSERT INTO public.product_variants (product_id,label,mrp,price,stock,sku,sort_order)
SELECT p.id,v.label,v.mrp,v.price,v.stock,v.sku,v.so FROM (VALUES
('fortune-chakki-fresh-atta','5 kg',300,275,40,'FORTUNE-5KG',0),
('fortune-chakki-fresh-atta','10 kg',580,529,18,'FORTUNE-10KG',1),
('aashirvaad-shudh-chakki-atta','5 kg',320,295,32,'AASHIRVAAD-5KG',0),
('aashirvaad-shudh-chakki-atta','10 kg',620,575,12,'AASHIRVAAD-10KG',1),
('rajdhani-besan','500 g',70,62,45,'RAJDHANI-500G',0),
('rajdhani-besan','1 kg',135,119,25,'RAJDHANI-1KG',1),
('bansi-suji-rava','500 g',42,36,50,'BANSISUJI-500G',0),
('bansi-suji-rava','1 kg',80,69,30,'BANSISUJI-1KG',1),
('shakti-bhog-maida','500 g',38,33,40,'SHAKTIMAIDA-500G',0),
('shakti-bhog-maida','1 kg',72,64,22,'SHAKTIMAIDA-1KG',1),
('india-gate-classic-basmati-rice','1 kg',165,148,35,'INDIAGATE-1KG',0),
('india-gate-classic-basmati-rice','5 kg',790,725,14,'INDIAGATE-5KG',1),
('daawat-rozana-gold-basmati','1 kg',120,105,40,'DAAWAT-1KG',0),
('daawat-rozana-gold-basmati','5 kg',560,515,16,'DAAWAT-5KG',1),
('sona-masoori-rice-local','5 kg',320,289,28,'SONAMASOORI-5KG',0),
('sona-masoori-rice-local','10 kg',620,569,10,'SONAMASOORI-10KG',1),
('tata-sampann-toor-dal','500 g',95,86,50,'TOORDAL-500G',0),
('tata-sampann-toor-dal','1 kg',180,165,30,'TOORDAL-1KG',1),
('moong-dal-dhuli','500 g',85,76,45,'MOONGDAL-500G',0),
('moong-dal-dhuli','1 kg',165,148,22,'MOONGDAL-1KG',1),
('masoor-dal','500 g',70,62,48,'MASOORDAL-500G',0),
('masoor-dal','1 kg',135,122,26,'MASOORDAL-1KG',1),
('rajma-chitra','500 g',95,88,30,'RAJMA-500G',0),
('rajma-chitra','1 kg',185,172,15,'RAJMA-1KG',1),
('kabuli-chana','500 g',80,72,35,'KABULI-500G',0),
('kabuli-chana','1 kg',155,142,20,'KABULI-1KG',1),
('fortune-kachi-ghani-mustard-oil','1 L',175,159,40,'FORTMUST-1L',0),
('fortune-kachi-ghani-mustard-oil','2 L',345,315,20,'FORTMUST-2L',1),
('fortune-kachi-ghani-mustard-oil','5 L',850,789,10,'FORTMUST-5L',2),
('patanjali-kachi-ghani-sarson-tel','1 L',180,165,25,'PATSARSON-1L',0),
('patanjali-kachi-ghani-sarson-tel','5 L',880,819,8,'PATSARSON-5L',1),
('fortune-sunlite-refined-sunflower-oil','1 L',155,139,30,'FORTSUN-1L',0),
('fortune-sunlite-refined-sunflower-oil','5 L',760,699,12,'FORTSUN-5L',1),
('amul-pure-desi-ghee','500 ml',340,315,22,'AMULGHEE-500ML',0),
('amul-pure-desi-ghee','1 L',660,619,10,'AMULGHEE-1L',1),
('everest-turmeric-powder-haldi','100 g',38,34,60,'HALDI-100G',0),
('everest-turmeric-powder-haldi','200 g',72,64,35,'HALDI-200G',1),
('everest-turmeric-powder-haldi','500 g',170,155,15,'HALDI-500G',2),
('mdh-deggi-mirch','100 g',95,86,30,'DEGGI-100G',0),
('mdh-deggi-mirch','500 g',430,398,8,'DEGGI-500G',1),
('everest-garam-masala','50 g',55,49,40,'GARAM-50G',0),
('everest-garam-masala','100 g',105,94,25,'GARAM-100G',1),
('catch-jeera-whole','100 g',65,58,35,'JEERA-100G',0),
('catch-jeera-whole','200 g',125,112,18,'JEERA-200G',1),
('everest-dhaniya-powder','100 g',42,37,45,'DHANIYA-100G',0),
('everest-dhaniya-powder','500 g',190,172,12,'DHANIYA-500G',1),
('tata-salt-iodised','500 g',14,12,80,'TATASALT-500G',0),
('tata-salt-iodised','1 kg',28,25,60,'TATASALT-1KG',1),
('madhur-pure-sugar','1 kg',52,46,50,'SUGAR-1KG',0),
('madhur-pure-sugar','5 kg',255,232,15,'SUGAR-5KG',1),
('organic-gud-jaggery-block','500 g',50,44,30,'GUD-500G',0),
('organic-gud-jaggery-block','1 kg',95,85,20,'GUD-1KG',1),
('dabur-honey','250 g',165,149,25,'HONEY-250G',0),
('dabur-honey','500 g',320,289,12,'HONEY-500G',1),
('california-almonds-badam','250 g',290,265,20,'BADAM-250G',0),
('california-almonds-badam','500 g',560,519,10,'BADAM-500G',1),
('california-almonds-badam','1 kg',1090,999,5,'BADAM-1KG',2),
('whole-cashew-w320-kaju','250 g',310,285,15,'KAJU-250G',0),
('whole-cashew-w320-kaju','500 g',610,565,8,'KAJU-500G',1),
('kishmish-raisins','250 g',110,98,25,'KISHMISH-250G',0),
('kishmish-raisins','500 g',210,189,12,'KISHMISH-500G',1),
('tata-tea-premium','250 g',145,132,40,'TATATEA-250G',0),
('tata-tea-premium','500 g',285,259,20,'TATATEA-500G',1),
('tata-tea-premium','1 kg',560,519,8,'TATATEA-1KG',2),
('red-label-natural-care-tea','250 g',150,138,30,'REDLABEL-250G',0),
('red-label-natural-care-tea','500 g',295,272,14,'REDLABEL-500G',1),
('nescafe-classic-instant-coffee','50 g',180,165,20,'NESCAFE-50G',0),
('nescafe-classic-instant-coffee','100 g',340,309,10,'NESCAFE-100G',1),
('parle-g-original-glucose-biscuits','Rs.10 pack',10,10,100,'PARLEG-10',0),
('parle-g-original-glucose-biscuits','800 g Family',90,84,25,'PARLEG-800G',1),
('britannia-good-day-cashew-cookies','100 g',30,27,60,'GOODDAY-100G',0),
('britannia-good-day-cashew-cookies','600 g',150,139,18,'GOODDAY-600G',1),
('sunfeast-marie-light','250 g',40,36,45,'MARIE-250G',0),
('haldiram-s-aloo-bhujia','200 g',55,50,50,'BHUJIA-200G',0),
('haldiram-s-aloo-bhujia','400 g',105,95,25,'BHUJIA-400G',1),
('bikaji-bikaneri-bhujia','200 g',52,47,40,'BIKAJI-200G',0),
('bikaji-bikaneri-bhujia','400 g',100,92,20,'BIKAJI-400G',1),
('lay-s-india-s-magic-masala','Rs.20 pack',20,20,80,'LAYS-20',0),
('lay-s-india-s-magic-masala','Rs.50 pack',50,48,40,'LAYS-50',1),
('cadbury-dairy-milk','13.2 g',10,10,100,'DAIRYMILK-13G',0),
('cadbury-dairy-milk','50 g',45,42,50,'DAIRYMILK-50G',1),
('maggi-2-minute-masala-noodles','70 g single',14,13,120,'MAGGI-70G',0),
('maggi-2-minute-masala-noodles','4 pack',56,52,60,'MAGGI-4PK',1),
('maggi-2-minute-masala-noodles','12 pack',168,155,20,'MAGGI-12PK',2),
('sunfeast-yippee-pasta-masala','70 g',30,27,40,'YIPPEE-70G',0),
('kissan-fresh-tomato-ketchup','500 g',110,99,30,'KISSAN-500G',0),
('kissan-fresh-tomato-ketchup','950 g',180,165,15,'KISSAN-950G',1),
('mother-s-recipe-mango-pickle','400 g',95,86,25,'ACHAR-400G',0),
('amul-taaza-toned-milk','500 ml',29,28,60,'AMULMILK-500ML',0),
('amul-taaza-toned-milk','1 L',75,72,30,'AMULMILK-1L',1),
('amul-butter','100 g',58,55,40,'AMULBUTTER-100G',0),
('amul-butter','500 g',275,265,15,'AMULBUTTER-500G',1),
('bisleri-mineral-water','1 L',20,19,60,'BISLERI-1L',0),
('bisleri-mineral-water','2 L',35,32,30,'BISLERI-2L',1),
('coca-cola-soft-drink','750 ml',45,42,40,'COKE-750ML',0),
('coca-cola-soft-drink','1.25 L',70,65,20,'COKE-1250ML',1),
('real-mixed-fruit-juice','1 L',120,110,25,'REALJUICE-1L',0),
('kellogg-s-corn-flakes','475 g',235,215,18,'CORNFLAKES-475G',0),
('aashirvaad-poha','500 g',45,40,40,'POHA-500G',0),
('saffola-oats','500 g',99,89,25,'OATS-500G',0),
('saffola-oats','1 kg',190,172,12,'OATS-1KG',1),
('johnson-s-baby-powder','100 g',95,88,25,'JBPOWDER-100G',0),
('johnson-s-baby-powder','400 g',290,269,10,'JBPOWDER-400G',1),
('pampers-baby-dry-pants','M - 9 pcs',199,182,20,'PAMPERS-M9',0),
('pampers-baby-dry-pants','L - 9 pcs',219,199,15,'PAMPERS-L9',1),
('lifebuoy-total-10-soap','125 g x1',38,34,60,'LIFEBUOY-1',0),
('lifebuoy-total-10-soap','Pack of 4',152,132,25,'LIFEBUOY-4',1),
('dettol-handwash-refill','750 ml',165,145,20,'DETTOLHW-750',0),
('parachute-coconut-hair-oil','175 ml',95,88,40,'PARACHUTE-175',0),
('parachute-coconut-hair-oil','500 ml',245,225,18,'PARACHUTE-500',1),
('clinic-plus-strong-long-shampoo','175 ml',99,90,30,'CLINIC-175',0),
('clinic-plus-strong-long-shampoo','340 ml',185,169,15,'CLINIC-340',1),
('nivea-soft-light-moisturiser','100 ml',199,179,15,'NIVEA-100',0),
('colgate-strong-teeth-toothpaste','100 g',60,55,50,'COLGATE-100G',0),
('colgate-strong-teeth-toothpaste','300 g',165,152,20,'COLGATE-300G',1),
('lizol-disinfectant-floor-cleaner','500 ml',115,102,25,'LIZOL-500',0),
('lizol-disinfectant-floor-cleaner','975 ml',210,189,12,'LIZOL-975',1),
('harpic-power-plus-toilet-cleaner','500 ml',99,89,25,'HARPIC-500',0),
('harpic-power-plus-toilet-cleaner','1 L',185,168,12,'HARPIC-1L',1),
('vim-dishwash-bar','140 g',10,10,80,'VIM-140G',0),
('vim-dishwash-bar','300 g',25,23,50,'VIM-300G',1),
('surf-excel-easy-wash-detergent-powder','500 g',70,63,40,'SURF-500G',0),
('surf-excel-easy-wash-detergent-powder','1 kg',135,122,25,'SURF-1KG',1),
('surf-excel-easy-wash-detergent-powder','4 kg',520,479,8,'SURF-4KG',2),
('rin-detergent-bar','250 g',20,18,60,'RIN-250G',0),
('comfort-fabric-conditioner','860 ml',210,189,12,'COMFORT-860',0),
('scotch-brite-scrub-pad','Pack of 3',65,58,30,'SCOTCH-3',0),
('homefoil-aluminium-foil','9 m',75,68,25,'FOIL-9M',0),
('cycle-pure-agarbatti-three-in-one','Small pack',35,32,50,'AGARBATTI-S',0),
('cycle-pure-agarbatti-three-in-one','Large pack',95,86,25,'AGARBATTI-L',1),
('mangaldeep-camphor-kapoor','50 g',70,63,30,'KAPOOR-50G',0),
('classmate-notebook-172-pages','1 pc',45,40,60,'NOTEBOOK-1',0),
('classmate-notebook-172-pages','Pack of 6',270,239,15,'NOTEBOOK-6',1),
('cello-butterflow-ball-pen','1 pc',10,10,100,'PEN-1',0),
('cello-butterflow-ball-pen','Pack of 5',50,45,40,'PEN-5',1),
('pedigree-adult-dog-food-chicken','1.2 kg',340,315,10,'PEDIGREE-1200',0)
) AS v(pslug,label,mrp,price,stock,sku,so) JOIN public.products p ON p.slug=v.pslug;

INSERT INTO public.coupons (code,description,discount_type,value,min_order,max_discount) VALUES
('WELCOME50','Flat Rs.50 off on orders above Rs.499','flat',50,499,NULL),
('SAVE10','10% off on orders above Rs.999 (max Rs.150)','percent',10,999,150),
('DIWALI15','Festival offer: 15% off above Rs.1499 (max Rs.300)','percent',15,1499,300);
